-- =============================================================================
-- CockroachDB native migration: 001_pragmas.sql
-- Source (logic): supabase/migrations/__pragmas__
-- Transformed for CockroachDB (INT4, no Supabase extensions/realtime, portable RLS).
-- Generated by: node cockroachdb/scripts/generate-native-migrations.mjs
-- =============================================================================
SET default_int_size = 4;

-- Session defaults for Postgres-like INTEGER (INT4).
