-- =============================================================================
-- CockroachDB native migration: 031_realtime_experiences.sql
-- Source (logic): supabase/migrations/20260507190000_realtime_experiences.sql
-- Transformed for CockroachDB (INT4, no Supabase extensions/realtime, portable RLS).
-- Generated by: node cockroachdb/scripts/generate-native-migrations.mjs
-- =============================================================================
SET default_int_size = 4;


-- =============================================================================
-- Migration: 20260507190000_realtime_experiences
-- Purpose: Register app tables with supabase_realtime and set REPLICA IDENTITY
--          FULL so Postgres logical replication emits complete row images for
--          UPDATE/DELETE fan-out to browser clients.
-- Prerequisites:
--   - supabase_realtime publication exists (Supabase default).
--   - Listed tables already created in prior platform migrations.
-- Apply-time behavior:
--   - Idempotent DO block adds each table to supabase_realtime (ignores dupes).
--   - Sets replica identity full on chat, billing, research, and storage tables.
-- Security / RLS:
--   - Does not change RLS or grants. Realtime still respects RLS on the
--     subscribing role; clients only receive events for rows they can SELECT.
-- Rollback guidance:
--   - ALTER PUBLICATION supabase_realtime DROP TABLE for each table added.
--   - ALTER TABLE ... REPLICA IDENTITY DEFAULT (may break UPDATE payloads).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Publication membership: supabase_realtime
-- Swallows duplicate_object / undefined_object so re-runs are safe.
-- -----------------------------------------------------------------------------
-- CRDB: omitted foreach publication block
;

-- -----------------------------------------------------------------------------
-- Replica identity: FULL row images for logical replication
-- Required for Supabase Realtime to deliver old+new column values on UPDATE.
-- -----------------------------------------------------------------------------
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY
-- omitted on CRDB: REPLICA IDENTITY

