-- =============================================================================
-- CockroachDB native migration: 040_security_hardening.sql
-- Source (logic): supabase/migrations/20260507200000_security_advisor_hardening.sql
-- Transformed for CockroachDB (INT4, no Supabase extensions/realtime, portable RLS).
-- Generated by: node cockroachdb/scripts/generate-native-migrations.mjs
-- =============================================================================
SET default_int_size = 4;


-- =============================================================================
-- Migration: 20260507200000_security_advisor_hardening
-- Purpose: Address Supabase Security Advisor findings by pinning function
--          search_path, moving vector into extensions schema, and restricting
--          SECURITY DEFINER RPCs to service_role only.
-- Prerequisites:
--   - public.* functions listed below already exist.
--   - extensions schema creatable (Supabase pattern).
-- Apply-time behavior:
--   - Creates extensions schema; sets search_path on helper/trigger functions.
--   - Moves pgvector extension to extensions schema when present.
--   - Revokes EXECUTE from public/anon/authenticated on sensitive RPCs;
--     grants EXECUTE to service_role only (two signature batches).
-- Security / RLS:
--   - No table RLS changes. Reduces search_path hijack risk on SECURITY
--     DEFINER functions and prevents direct client invocation of billing/chat
--     RPCs via PostgREST.
-- Rollback guidance:
--   - Re-grant EXECUTE to authenticated where intentionally exposed (avoid).
--   - ALTER EXTENSION vector SET SCHEMA public only if required by tooling.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Schema: extensions (isolated extension objects)
-- -----------------------------------------------------------------------------
create schema if not exists extensions;

-- -----------------------------------------------------------------------------
-- search_path hardening on trigger/helper functions
-- Prevents malicious objects in public from shadowing builtins/extensions.
-- -----------------------------------------------------------------------------
-- omitted on CRDB: ALTER FUNCTION ... SET search_path


-- omitted on CRDB: ALTER FUNCTION ... SET search_path


-- omitted on CRDB: ALTER FUNCTION ... SET search_path


-- omitted on CRDB: ALTER FUNCTION ... SET search_path


-- omitted on CRDB: ALTER FUNCTION ... SET search_path


-- -----------------------------------------------------------------------------
-- Extension placement: vector in extensions schema
-- -----------------------------------------------------------------------------
do $$
begin
  alter extension vector set schema extensions;
exception
  when undefined_object then null;
end $$;

-- -----------------------------------------------------------------------------
-- RPC lockdown batch 1: application SECURITY DEFINER functions
-- Revoke from API roles; backend uses service_role key for these calls.
-- -----------------------------------------------------------------------------
-- CRDB: omitted PL/pgSQL FOREACH block
;

-- -----------------------------------------------------------------------------
-- RPC lockdown batch 2: internal trigger/helper functions
-- -----------------------------------------------------------------------------
-- CRDB: omitted PL/pgSQL FOREACH block
;

