-- =============================================================================
-- CockroachDB native migration: 043_fk_indexes.sql
-- Source (logic): supabase/migrations/20260507204000_performance_advisor_fk_indexes.sql
-- Transformed for CockroachDB (INT4, no Supabase extensions/realtime, portable RLS).
-- Generated by: node cockroachdb/scripts/generate-native-migrations.mjs
-- =============================================================================
SET default_int_size = 4;


-- =============================================================================
-- Migration: 20260507204000_performance_advisor_fk_indexes
-- Purpose: Add btree indexes on unindexed foreign-key columns flagged by
--          Supabase Performance Advisor; drop only redundant indexes superseded
--          by UNIQUE constraints or newer strategic indexes.
-- Prerequisites:
--   - Platform schema tables/FKs from prior migrations exist.
-- Apply-time behavior:
--   - CREATE INDEX IF NOT EXISTS per FK column listed below.
--   - DROP INDEX on research_runs_provider_run_idx, webhook_events_provider_event_idx,
--     embeddings_chunk_idx (redundant with unique/covering indexes).
-- Security / RLS:
--   - Index-only; no grant or policy changes.
-- Rollback guidance:
--   - DROP INDEX for indexes created here if storage/ write overhead is a concern.
--   - Recreate dropped indexes only if query plans regress.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- abuse / api keys
-- -----------------------------------------------------------------------------
create index if not exists abuse_reports_user_id_fk_idx on public.abuse_reports (user_id);

create index if not exists abuse_reports_workspace_id_fk_idx on public.abuse_reports (workspace_id);

create index if not exists api_keys_user_id_fk_idx on public.api_keys (user_id);

create index if not exists api_keys_workspace_id_fk_idx on public.api_keys (workspace_id);

-- -----------------------------------------------------------------------------
-- artifacts / artifact jobs / versions
-- -----------------------------------------------------------------------------
create index if not exists artifact_jobs_artifact_id_fk_idx on public.artifact_jobs (artifact_id);

create index if not exists artifact_jobs_user_id_fk_idx on public.artifact_jobs (user_id);

create index if not exists artifact_jobs_workspace_id_fk_idx on public.artifact_jobs (workspace_id);

create index if not exists artifact_versions_created_by_message_id_fk_idx on public.artifact_versions (created_by_message_id);

create index if not exists artifacts_chat_id_fk_idx on public.artifacts (chat_id);

create index if not exists artifacts_current_version_id_fk_idx on public.artifacts (current_version_id);

create index if not exists artifacts_message_id_fk_idx on public.artifacts (message_id);

create index if not exists artifacts_workspace_id_fk_idx on public.artifacts (workspace_id);

-- -----------------------------------------------------------------------------
-- audit / billing
-- -----------------------------------------------------------------------------
create index if not exists audit_logs_user_id_fk_idx on public.audit_logs (user_id);

create index if not exists billing_orders_workspace_id_fk_idx on public.billing_orders (workspace_id);

create index if not exists billing_payments_order_id_fk_idx on public.billing_payments (order_id);

create index if not exists billing_payments_user_id_fk_idx on public.billing_payments (user_id);

create index if not exists billing_payments_workspace_id_fk_idx on public.billing_payments (workspace_id);

-- -----------------------------------------------------------------------------
-- chat branches / messages / parts / reactions
-- -----------------------------------------------------------------------------
create index if not exists chat_branch_states_user_id_fk_idx on public.chat_branch_states (user_id);

create index if not exists chat_branches_chat_id_fk_idx on public.chat_branches (chat_id);

create index if not exists chat_branches_created_by_fk_idx on public.chat_branches (created_by);

create index if not exists chat_branches_created_from_message_id_fk_idx on public.chat_branches (created_from_message_id);

create index if not exists chat_branches_parent_branch_id_fk_idx on public.chat_branches (parent_branch_id);

create index if not exists chat_branches_root_message_id_fk_idx on public.chat_branches (root_message_id);

create index if not exists chat_message_parts_artifact_id_fk_idx on public.chat_message_parts (artifact_id);

create index if not exists chat_message_parts_file_id_fk_idx on public.chat_message_parts (file_id);

create index if not exists chat_message_parts_tool_call_id_fk_idx on public.chat_message_parts (tool_call_id);

create index if not exists chat_message_reactions_user_id_fk_idx on public.chat_message_reactions (user_id);

create index if not exists chat_messages_parent_message_id_fk_idx on public.chat_messages (parent_message_id);

create index if not exists chat_messages_user_id_fk_idx on public.chat_messages (user_id);

create index if not exists chats_project_id_fk_idx on public.chats (project_id);

-- -----------------------------------------------------------------------------
-- documents / embeddings / files
-- -----------------------------------------------------------------------------
create index if not exists document_chunks_user_id_fk_idx on public.document_chunks (user_id);

create index if not exists document_chunks_workspace_id_fk_idx on public.document_chunks (workspace_id);

create index if not exists embeddings_user_id_fk_idx on public.embeddings (user_id);

create index if not exists embeddings_workspace_id_fk_idx on public.embeddings (workspace_id);

create index if not exists file_processing_jobs_file_id_fk_idx on public.file_processing_jobs (file_id);

create index if not exists file_processing_jobs_user_id_fk_idx on public.file_processing_jobs (user_id);

-- -----------------------------------------------------------------------------
-- gifts / library / model usage
-- -----------------------------------------------------------------------------
create index if not exists gift_codes_plan_id_fk_idx on public.gift_codes (plan_id);

create index if not exists gift_codes_redeemed_by_user_id_fk_idx on public.gift_codes (redeemed_by_user_id);

create index if not exists gift_delivery_jobs_user_id_fk_idx on public.gift_delivery_jobs (user_id);

create index if not exists gift_redemptions_subscription_id_fk_idx on public.gift_redemptions (subscription_id);

create index if not exists gift_redemptions_token_transaction_id_fk_idx on public.gift_redemptions (token_transaction_id);

create index if not exists gift_redemptions_user_id_fk_idx on public.gift_redemptions (user_id);

create index if not exists library_items_user_id_fk_idx on public.library_items (user_id);

create index if not exists library_items_workspace_id_fk_idx on public.library_items (workspace_id);

create index if not exists model_usage_events_chat_id_fk_idx on public.model_usage_events (chat_id);

create index if not exists model_usage_events_message_id_fk_idx on public.model_usage_events (message_id);

create index if not exists model_usage_events_workspace_id_fk_idx on public.model_usage_events (workspace_id);

-- -----------------------------------------------------------------------------
-- pins / profiles / projects / research
-- -----------------------------------------------------------------------------
create index if not exists pinned_chats_user_id_fk_idx on public.pinned_chats (user_id);

create index if not exists profiles_default_workspace_id_fk_idx on public.profiles (default_workspace_id);

create index if not exists project_members_user_id_fk_idx on public.project_members (user_id);

create index if not exists projects_workspace_id_fk_idx on public.projects (workspace_id);

create index if not exists research_runs_chat_id_fk_idx on public.research_runs (chat_id);

create index if not exists research_runs_workspace_id_fk_idx on public.research_runs (workspace_id);

create index if not exists research_sources_research_run_id_fk_idx on public.research_sources (research_run_id);

-- -----------------------------------------------------------------------------
-- saved prompts / subscriptions / tokens / tools
-- -----------------------------------------------------------------------------
create index if not exists saved_prompts_user_id_fk_idx on public.saved_prompts (user_id);

create index if not exists saved_prompts_workspace_id_fk_idx on public.saved_prompts (workspace_id);

create index if not exists subscription_activation_events_billing_order_id_fk_idx on public.subscription_activation_events (billing_order_id);

create index if not exists subscription_activation_events_plan_id_fk_idx on public.subscription_activation_events (plan_id);

create index if not exists subscription_activation_events_subscription_id_fk_idx on public.subscription_activation_events (subscription_id);

create index if not exists subscription_activation_events_user_id_fk_idx on public.subscription_activation_events (user_id);

create index if not exists subscription_activation_events_workspace_id_fk_idx on public.subscription_activation_events (workspace_id);

create index if not exists subscriptions_plan_id_fk_idx on public.subscriptions (plan_id);

create index if not exists subscriptions_workspace_id_fk_idx on public.subscriptions (workspace_id);

create index if not exists token_transactions_workspace_id_fk_idx on public.token_transactions (workspace_id);

create index if not exists tool_calls_chat_id_fk_idx on public.tool_calls (chat_id);

create index if not exists tool_calls_user_id_fk_idx on public.tool_calls (user_id);

create index if not exists tool_calls_workspace_id_fk_idx on public.tool_calls (workspace_id);

-- -----------------------------------------------------------------------------
-- usage rollups / balances / files / security / workspace invites
-- -----------------------------------------------------------------------------
create index if not exists usage_daily_rollups_workspace_id_fk_idx on public.usage_daily_rollups (workspace_id);

create index if not exists user_balances_workspace_id_fk_idx on public.user_balances (workspace_id);

create index if not exists user_files_project_id_fk_idx on public.user_files (project_id);

create index if not exists user_files_workspace_id_fk_idx on public.user_files (workspace_id);

create index if not exists user_objects_user_id_fk_idx on public.user_objects (user_id);

create index if not exists user_security_events_user_id_fk_idx on public.user_security_events (user_id);

create index if not exists workspace_invites_invited_by_fk_idx on public.workspace_invites (invited_by);

create index if not exists workspace_invites_workspace_id_fk_idx on public.workspace_invites (workspace_id);

-- -----------------------------------------------------------------------------
-- Drop redundant indexes (superseded by UNIQUE or newer covering indexes)
-- Keep strategic indexes even if idx_scan is zero on fresh databases.
-- -----------------------------------------------------------------------------
drop index if exists public.research_runs_provider_run_idx;

drop index if exists public.webhook_events_provider_event_idx;

drop index if exists public.embeddings_chunk_idx;

