-- =============================================================================
-- CockroachDB native migration: 061_extension_schema.sql
-- Source (logic): supabase/migrations/20260508103000_extension_schema_corrections.sql
-- Transformed for CockroachDB (INT4, no Supabase extensions/realtime, portable RLS).
-- Generated by: node cockroachdb/scripts/generate-native-migrations.mjs
-- =============================================================================
SET default_int_size = 4;

CREATE SCHEMA IF NOT EXISTS pgmq;
