-- =============================================================================
-- CockroachDB native migration: 065_safe_app_access.sql
-- Source (logic): supabase/migrations/20260508107000_safe_app_access_after_graphql_lockdown.sql
-- Transformed for CockroachDB (INT4, no Supabase extensions/realtime, portable RLS).
-- Generated by: node cockroachdb/scripts/generate-native-migrations.mjs
-- =============================================================================
SET default_int_size = 4;


-- =============================================================================
-- Migration: 20260508107000_safe_app_access_after_graphql_lockdown
-- Purpose: Restore minimal app-safe access after 20260508105000 lockdown:
--   - Drop pg_graphql from production until an explicit surface is designed.
--   - Keep anon off raw public tables.
--   - Grant authenticated SELECT only on RLS-protected Realtime tables.
--   - Re-enable RLS, publication membership, and REPLICA IDENTITY FULL.
-- Prerequisites:
--   - 20260508105000_security_advisor_graphql_lockdown.sql applied.
--   - RLS owner/member policies exist on listed tables from platform migrations.
-- Apply-time behavior:
--   - DROP EXTENSION pg_graphql; drop graphql/graphql_public schemas if present.
--   - REVOKE SELECT from public/anon; GRANT schema usage to authenticated.
--   - GRANT SELECT on enumerated tables to authenticated.
--   - Loop: ENABLE RLS, add to supabase_realtime, REPLICA IDENTITY FULL.
-- Security / RLS:
--   - Table grants allow PostgREST/Realtime connection; RLS enforces row access.
--   - anon has no table SELECT; writes remain service_role / RPC paths.
-- Rollback guidance:
--   - REVOKE authenticated SELECT; re-apply lockdown migration pattern if needed.
-- =============================================================================

drop extension if exists pg_graphql cascade;

-- -----------------------------------------------------------------------------
-- Remove graphql schemas if remnants exist
-- -----------------------------------------------------------------------------
-- CRDB: schema privilege hardening for graphql_public omitted (no matching Supabase extension schema)
-- CRDB: schema privilege hardening for graphql omitted (no matching Supabase extension schema)
;

-- -----------------------------------------------------------------------------
-- Narrow grants: authenticated Realtime tables only
-- -----------------------------------------------------------------------------
revoke select on all tables in schema public from public, anon;

revoke usage on schema public from anon;

grant usage on schema public to authenticated;

grant select on table
  public.chats,
  public.chat_messages,
  public.chat_branch_states,
  public.artifacts,
  public.file_processing_jobs,
  public.user_files,
  public.research_runs,
  public.subscriptions,
  public.subscription_activation_events,
  public.billing_orders,
  public.billing_payments,
  public.user_balances,
  public.gift_codes,
  public.gift_redemptions,
  public.token_transactions,
  public.user_objects
to authenticated;

-- -----------------------------------------------------------------------------
-- Ensure RLS + Realtime publication + full replica identity per app table
-- -----------------------------------------------------------------------------
-- CRDB: omitted foreach publication + RLS block
;

