-- =============================================================================
-- CockroachDB native migration: 066_index_cleanup.sql
-- Source (logic): supabase/migrations/20260508108000_conservative_unused_index_cleanup.sql
-- Transformed for CockroachDB (INT4, no Supabase extensions/realtime, portable RLS).
-- Generated by: node cockroachdb/scripts/generate-native-migrations.mjs
-- =============================================================================
SET default_int_size = 4;


-- =============================================================================
-- Migration: 20260508108000_conservative_unused_index_cleanup
-- Purpose: Drop only indexes that are superseded or have no current query
--          surface, responding conservatively to Performance Advisor unused_index
--          INFOs (idx_scan=0 on young databases is not proof of uselessness).
-- Prerequisites:
--   - 20260508102000_platform_extension_identity_expansion.sql created unaccent
--     tsvector indexes used by search_user_messages / match_document_chunks.
-- Apply-time behavior:
--   - DROP INDEX on legacy GIN/trigram/JSONB search indexes listed below.
-- Security / RLS:
--   - Index-only; no data or policy changes.
-- Rollback guidance:
--   - Recreate dropped indexes from git if a feature starts using those columns.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Superseded GIN indexes (replaced by content_search_unaccent columns)
-- -----------------------------------------------------------------------------
drop index if exists public.chat_messages_content_search_gin_idx;

drop index if exists public.document_chunks_content_search_gin_idx;

-- -----------------------------------------------------------------------------
-- Speculative JSONB GIN indexes (no current containment queries)
-- document_chunks_metadata_gin_idx retained for match_document_chunks filter.
-- -----------------------------------------------------------------------------
drop index if exists public.chats_metadata_gin_idx;

drop index if exists public.artifacts_metadata_gin_idx;

-- -----------------------------------------------------------------------------
-- Speculative trigram indexes (no ilike/% operator queries in app today)
-- -----------------------------------------------------------------------------
drop index if exists public.chats_title_trgm_idx;

drop index if exists public.artifacts_title_trgm_idx;

drop index if exists public.user_files_original_name_trgm_idx;

drop index if exists public.saved_prompts_title_trgm_idx;

drop index if exists public.assistant_profiles_name_trgm_idx;

drop index if exists public.connector_catalog_name_trgm_idx;

drop index if exists public.user_memories_summary_trgm_idx;

