serve:
  cookies:
    same_site_mode: Lax
  public:
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:9002
      allow_credentials: true

urls:
  self:
    issuer: http://127.0.0.1:4444/
  consent: http://localhost:9002/
  login: http://localhost:9002/
  logout: http://localhost:9002/

secrets:
  system:
    - change-me-ory-hydra-system-secret-32chars

dsn: postgres://ory:ory@ory-postgres:5432/ory?sslmode=disable

log:
  level: info
