
export const indianLanguages = [
    { name: "Assamese", native: "অসমীয়া (Assamese)" },
    { name: "Bengali", native: "বাংলা (Bengali)" },
    { name: "Bodo", native: "बोड़ो (Bodo)" },
    { name: "Dogri", native: "डोगरी (Dogri)" },
    { name: "Gujarati", native: "ગુજરાતી (Gujarati)" },
    { name: "Hindi", native: "हिन्दी (Hindi)" },
    { name: "Kannada", native: "ಕನ್ನಡ (Kannada)" },
    { name: "Kashmiri", native: "कश्मीरी (Kashmiri)" },
    { name: "Konkani", native: "कोंकणी (Konkani)" },
    { name: "Maithili", native: "मैथिली (Maithili)" },
    { name: "Malayalam", native: "മലയാളം (Malayalam)" },
    { name: "Manipuri", native: "মৈতৈলোন্ (Manipuri)" },
    { name: "Marathi", native: "मराठी (Marathi)" },
    { name: "Nepali", native: "नेपाली (Nepali)" },
    { name: "Odia", native: "ଓଡ଼ିଆ (Odia)" },
    { name: "Punjabi", native: "ਪੰਜਾਬੀ (Punjabi)" },
    { name: "Sanskrit", native: "संस्कृतम् (Sanskrit)" },
    { name: "Santali", native: "ᱥᱟᱱᱛᱟᱲᱤ (Santali)" },
    { name: "Sindhi", native: "सिन्धी (Sindhi)" },
    { name: "Tamil", native: "தமிழ் (Tamil)" },
    { name: "Telugu", native: "తెలుగు (Telugu)" },
    { name: "Urdu", native: "اردو (Urdu)" },
];

export const europeanLanguages = [
    { name: "Albanian", native: "Shqip (Albanian)" },
    { name: "Basque", native: "Euskara (Basque)" },
    { name: "Belarusian", native: "Беларуская (Belarusian)" },
    { name: "Bosnian", native: "Bosanski (Bosnian)" },
    { name: "Bulgarian", native: "Български (Bulgarian)" },
    { name: "Catalan", native: "Català (Catalan)" },
    { name: "Croatian", native: "Hrvatski (Croatian)" },
    { name: "Czech", native: "Čeština (Czech)" },
    { name: "Danish", native: "Dansk (Danish)" },
    { name: "Dutch", native: "Nederlands (Dutch)" },
    { name: "English (United Kingdom)", native: "English (United Kingdom)" },
    { name: "Estonian", native: "Eesti (Estonian)" },
    { name: "Faroese", native: "Føroyskt (Faroese)" },
    { name: "Finnish", native: "Suomi (Finnish)" },
    { name: "French", native: "Français (French)" },
    { name: "Galician", native: "Galego (Galician)" },
    { name: "German", native: "Deutsch (German)" },
    { name: "Greek", native: "Ελληνικά (Greek)" },
    { name: "Hungarian", native: "Magyar (Hungarian)" },
    { name: "Icelandic", native: "Íslenska (Icelandic)" },
    { name: "Irish", native: "Gaeilge (Irish)" },
    { name: "Italian", native: "Italiano (Italian)" },
    { name: "Latvian", native: "Latviešu (Latvian)" },
    { name: "Lithuanian", native: "Lietuvių (Lithuanian)" },
    { name: "Luxembourgish", native: "Lëtzebuergesch (Luxembourgish)" },
    { name: "Macedonian", native: "Македонски (Macedonian)" },
    { name: "Maltese", native: "Malti (Maltese)" },
    { name: "Norwegian", native: "Norsk (Norwegian)" },
    { name: "Polish", native: "Polski (Polish)" },
    { name: "Portuguese", native: "Português (Portuguese)" },
    { name: "Romanian", native: "Română (Romanian)" },
    { name: "Russian", native: "Русский (Russian)" },
    { name: "Scottish Gaelic", native: "Gàidhlig (Scottish Gaelic)" },
    { name: "Serbian", native: "Српски (Serbian)" },
    { name: "Slovak", native: "Slovenčina (Slovak)" },
    { name: "Slovenian", native: "Slovenščina (Slovenian)" },
    { name: "Spanish", native: "Español (Spanish)" },
    { name: "Swedish", native: "Svenska (Swedish)" },
    { name: "Ukrainian", native: "Українська (Ukrainian)" },
    { name: "Welsh", native: "Cymraeg (Welsh)" },
];

export const middleEasternLanguages = [
    { name: "Arabic", native: "العربية (Arabic)" },
    { name: "Armenian", native: "Հայերեն (Armenian)" },
    { name: "Azerbaijani", native: "Azərbaycanca (Azerbaijani)" },
    { name: "Georgian", native: "ქართული (Georgian)" },
    { name: "Hebrew", native: "עברית (Hebrew)" },
    { name: "Kurdish", native: "Kurdî (Kurdish)" },
    { name: "Persian", native: "فارسی (Persian)" },
    { name: "Turkish", native: "Türkçe (Turkish)" },
];

export const eastAsianLanguages = [
    { name: "Chinese (Simplified)", native: "中文 (简体) (Chinese, Simplified)" },
    { name: "Chinese (Traditional)", native: "中文 (繁體) (Chinese, Traditional)" },
    { name: "Japanese", native: "日本語 (Japanese)" },
    { name: "Korean", native: "한국어 (Korean)" },
    { name: "Mongolian", native: "Монгол (Mongolian)" },
];

export const southeastAsianLanguages = [
    { name: "Burmese", native: "မြန်မာစာ (Burmese)" },
    { name: "Cebuano", native: "Cebuano" },
    { name: "Filipino", native: "Filipino" },
    { name: "Indonesian", native: "Bahasa Indonesia (Indonesian)" },
    { name: "Javanese", native: "Basa Jawa (Javanese)" },
    { name: "Khmer", native: "ខ្មែរ (Khmer)" },
    { name: "Lao", native: "ລາว (Lao)" },
    { name: "Malay", native: "Bahasa Melayu (Malay)" },
    { name: "Sundanese", native: "Basa Sunda (Sundanese)" },
    { name: "Thai", native: "ไทย (Thai)" },
    { name: "Vietnamese", native: "Tiếng Việt (Vietnamese)" },
];

export const africanLanguages = [
    { name: "Afrikaans", native: "Afrikaans" },
    { name: "Amharic", native: "አማርኛ (Amharic)" },
    { name: "Chichewa", native: "Chichewa" },
    { name: "Hausa", native: "Hausa" },
    { name: "Igbo", native: "Asụsụ Igbo (Igbo)" },
    { name: "Kinyarwanda", native: "Ikinyarwanda (Kinyarwanda)" },
    { name: "Malagasy", native: "Malagasy" },
    { name: "Oromo", native: "Afaan Oromoo (Oromo)" },
    { name: "Sesotho", native: "Sesotho" },
    { name: "Shona", native: "chiShona (Shona)" },
    { name: "Somali", native: "Soomaali (Somali)" },
    { name: "Swahili", native: "Kiswahili (Swahili)" },
    { name: "Tigrinya", native: "ትግርኛ (Tigrinya)" },
    { name: "Xhosa", native: "isiXhosa (Xhosa)" },
    { name: "Yoruba", native: "Èdè Yorùbá (Yoruba)" },
    { name: "Zulu", native: "isiZulu (Zulu)" },
];

export const americasLanguages = [
    { name: "English (United States)", native: "English (United States)", active: true },
    { name: "French (Canada)", native: "Français (Canada)" },
    { name: "Haitian Creole", native: "Kreyòl Ayisyen (Haitian Creole)" },
    { name: "Quechua", native: "Runasimi (Quechua)" },
    { name: "Portuguese (Brazil)", native: "Português (Brasil)" },
    { name: "Spanish (Latin America)", native: "Español (Latinoamérica)" },
];
