import {
  fileNameFromPath,
  type ChatArtifact,
} from "@/lib/chat-artifacts";

export type CreateFileBlock = {
  id: string;
  path: string;
  title: string;
  language: string;
  content: string;
  isComplete: boolean;
};

export type ParsedAssistantSegment =
  | { type: "markdown"; content: string }
  | { type: "create_file"; block: CreateFileBlock };

const CREATE_FILE_OPEN_RE = /<create_file\b([^>]*)>/gi;
const CREATE_FILE_CLOSE = "</create_file>";

function isGeneratedFooter(line: string): boolean {
  const stripped = line.replace(/^[-*_]\s*/, "").trim();
  return (
    (stripped.startsWith("This ") || stripped.startsWith("Generated by clauxen on ")) &&
    stripped.includes(" clauxen on ")
  );
}

export function parseTagAttributes(raw: string): Record<string, string> {
  const attrs: Record<string, string> = {};
  const pattern = /([\w-]+)\s*=\s*("([^"]*)"|'([^']*)')/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(raw)) !== null) {
    attrs[match[1]] = match[3] ?? match[4] ?? "";
  }
  return attrs;
}

export function inferLanguageFromPath(path: string): string {
  const ext = path.split(".").pop()?.toLowerCase() ?? "";
  const map: Record<string, string> = {
    md: "markdown",
    txt: "text",
    py: "python",
    js: "javascript",
    ts: "typescript",
    tsx: "typescript",
    jsx: "javascript",
    json: "json",
    html: "html",
    css: "css",
    sh: "bash",
    yml: "yaml",
    yaml: "yaml",
    rs: "rust",
    go: "go",
    java: "java",
    cpp: "cpp",
    c: "c",
  };
  return map[ext] ?? (ext || "text");
}

const LANGUAGE_TO_EXTENSION: Record<string, string> = {
  markdown: "md",
  text: "txt",
  plaintext: "txt",
  python: "py",
  javascript: "js",
  typescript: "ts",
  jsx: "jsx",
  tsx: "tsx",
  json: "json",
  html: "html",
  css: "css",
  scss: "scss",
  bash: "sh",
  shell: "sh",
  zsh: "sh",
  yaml: "yaml",
  rust: "rs",
  go: "go",
  java: "java",
  cpp: "cpp",
  c: "c",
  ruby: "rb",
  kotlin: "kt",
  swift: "swift",
  sql: "sql",
  php: "php",
  csharp: "cs",
  c_sharp: "cs",
};

/** Inverse of inferLanguageFromPath — used to name a downloaded code block file. */
export function extensionForLanguage(language: string): string {
  const normalized = language.trim().toLowerCase();
  return LANGUAGE_TO_EXTENSION[normalized] ?? (normalized || "txt");
}

function documentKindLabel(language: string): string {
  const normalized = language.toLowerCase();
  if (normalized === "markdown" || normalized === "md") return "Document";
  if (["python", "javascript", "typescript", "rust", "go", "java", "cpp", "c"].includes(normalized)) {
    return "Code";
  }
  return "File";
}

export function artifactMetaLabel(path: string, language: string): string {
  const ext = path.split(".").pop()?.toUpperCase() ?? language.toUpperCase();
  return `${documentKindLabel(language)} · ${ext}`;
}

/** Only markdown artifacts get a rendered preview; everything else opens in the code viewer. */
export function artifactSupportsPreview(
  path: string,
  language?: string,
): boolean {
  const ext = path.split(".").pop()?.toLowerCase();
  const normalized = language?.toLowerCase();
  return (
    ext === "md" ||
    ext === "markdown" ||
    normalized === "markdown" ||
    normalized === "md"
  );
}

export function stripGeneratedArtifactFooter(content: string): string {
  const lines = content.trimEnd().split("\n");
  if (lines.length === 0) return content;
  const lastLine = lines[lines.length - 1].trim();
  if (isGeneratedFooter(lastLine)) {
    lines.pop();
    if (lines.length > 0 && /^[-*_]{3,}$/.test(lines[lines.length - 1].trim())) {
      lines.pop();
    }
    return lines.join("\n").trimEnd();
  }
  return content;
}

function buildBlock(
  attrs: Record<string, string>,
  fileContent: string,
  isComplete: boolean,
  fallbackId: string,
): CreateFileBlock {
  const path = attrs.path || attrs.filename || attrs.name || "untitled.txt";
  const title =
    attrs.title ||
    attrs.label ||
    fileNameFromPath(path).replace(/\.[^.]+$/, "") ||
    "Untitled";
  const language = attrs.language || inferLanguageFromPath(path);

  return {
    id: path || fallbackId,
    path,
    title,
    language,
    content: stripGeneratedArtifactFooter(fileContent),
    isComplete,
  };
}

export function parseAssistantContentSegments(
  content: string,
): ParsedAssistantSegment[] {
  if (!content.includes("<create_file")) {
    return content ? [{ type: "markdown", content }] : [];
  }

  const segments: ParsedAssistantSegment[] = [];
  let cursor = 0;
  CREATE_FILE_OPEN_RE.lastIndex = 0;

  let match: RegExpExecArray | null;
  while ((match = CREATE_FILE_OPEN_RE.exec(content)) !== null) {
    const before = content.slice(cursor, match.index);
    if (before.trim()) {
      segments.push({ type: "markdown", content: before });
    }

    const attrs = parseTagAttributes(match[1] ?? "");
    const bodyStart = match.index + match[0].length;
    const rest = content.slice(bodyStart);
    const closeIdx = rest.toLowerCase().indexOf(CREATE_FILE_CLOSE.toLowerCase());

    if (closeIdx >= 0) {
      const fileContent = rest.slice(0, closeIdx);
      segments.push({
        type: "create_file",
        block: buildBlock(attrs, fileContent, true, `file-${match.index}`),
      });
      cursor = bodyStart + closeIdx + CREATE_FILE_CLOSE.length;
      CREATE_FILE_OPEN_RE.lastIndex = cursor;
    } else {
      segments.push({
        type: "create_file",
        block: buildBlock(attrs, rest, false, `file-stream-${match.index}`),
      });
      cursor = content.length;
      break;
    }
  }

  const tail = content.slice(cursor);
  if (tail.trim()) {
    segments.push({ type: "markdown", content: tail });
  }

  return segments;
}

export function collectCreateFileArtifacts(
  content: string,
  messageId: string,
): ChatArtifact[] {
  const segments = parseAssistantContentSegments(content);
  const artifacts: ChatArtifact[] = [];

  for (const segment of segments) {
    if (segment.type !== "create_file" || !segment.block.isComplete) continue;
    const block = segment.block;
    artifacts.push({
      id: `${messageId}:${block.id}`,
      path: block.path,
      fileName: fileNameFromPath(block.path),
      content: block.content,
      language: block.language,
      description: block.title,
      createdAtMs: Date.now(),
    });
  }

  return artifacts;
}

export function mergeChatArtifacts(
  existing: ChatArtifact[] | undefined,
  fromContent: ChatArtifact[],
): ChatArtifact[] {
  const map = new Map<string, ChatArtifact>();
  for (const artifact of existing ?? []) {
    map.set(artifact.id, artifact);
  }
  for (const artifact of fromContent) {
    map.set(artifact.id, artifact);
  }
  return [...map.values()].sort((a, b) => a.createdAtMs - b.createdAtMs);
}

export function stripCreateFileTags(content: string): string {
  return parseAssistantContentSegments(content)
    .filter((segment): segment is Extract<ParsedAssistantSegment, { type: "markdown" }> =>
      segment.type === "markdown",
    )
    .map((segment) => segment.content)
    .join("")
    .trim();
}
