/**
 * Single source of truth for all Clauxen system prompts.
 *
 * Consolidates:
 * - Identity + narrow-path prompts (chat, agent, thinking, title)
 * - Platform UI streaming contracts (`<create_file>`, bash_tool display)
 * - Model-authored base prompts (virgil.md and successors)
 * - Exa web-search system prompt
 *
 * Novita prompt-cache: keep static content first via buildModelSystemPrompt().
 */

import fs from "fs";
import path from "path";
import { buildInlineChatTitleSystemInstruction } from "@/lib/chat-title";
import type { ConfiguredModelId } from "@/lib/model-config";

// ─── Paths ───────────────────────────────────────────────────────────────────

export const MODEL_SYSTEM_PROMPTS_DIR = path.join(
  process.cwd(),
  "src",
  "models-system-prompts",
);

// ─── Identity ────────────────────────────────────────────────────────────────

/** Minimal identity anchor shared by narrow (non-.md) paths. */
export const CLAUXEN_IDENTITY =
  "You are Clauxen, a helpful AI assistant developed by Shirova AI, an Indian Based AI research lab focused on building autonomous agents and LLMs including safe and ethical AI models which can be beneficial for the society ";

// ─── Platform UI streaming (Clauxen web app) ─────────────────────────────────

/**
 * Appended after the model .md base prompt. Documents UI-visible streaming
 * tags and tool presentation — not part of the upstream Virgil clone.
 */
export const CLAUXEN_PLATFORM_UI_APPENDIX = `<clauxen_platform_ui>

<file_streaming_create_file_tags>
When the user should receive a downloadable/viewable file artifact in the Clauxen UI, stream the **full raw file body** inside a \`<create_file>\` tag in your assistant message:

<create_file path="/mnt/user-data/outputs/example.md" title="About Clauxen">
# Title
Full file content here — no markdown fences inside the tag.
</create_file>

Rules:
- Required attributes on the opening tag: \`path\` (absolute path, prefer /mnt/user-data/outputs/ for deliverables) and \`title\` (short card label).
- Optional: \`language\` (e.g. markdown, python) — otherwise inferred from the path extension.
- Put ONLY the file content between opening and closing tags. No commentary, no \`\`\` fences, no XML/HTML wrapper around the body.
- Stream the content naturally inside the block; emit \`</create_file>\` only after the entire file is written.
- After the closing tag, you may add one brief sentence outside the tag (e.g. "Here's the markdown file about myself.").
- Do NOT add generator footers or provenance lines inside files, such as "This document was generated by clauxen on ...".
- Supported extensions include .md, .txt, .py, .js, .ts, .tsx, .html, .json, .yaml, .sh, .css, and similar text formats.
- Use for standalone deliverables (reports, articles, scripts, configs) per artifact_usage_criteria in the base prompt.
- Do NOT nest create_file tags inside thinking blocks or other tags.
- Do NOT paste the same file content again as inline prose after the tag — the UI renders the artifact from the tag.

You may still call the \`create_file\` tool for sandbox writes; use streaming tags when the user should see content stream into the artifact panel and file card in chat.
\`create_file\` is the ONLY file-write tool — there is no separate edit tool. To change an existing file, call \`create_file\` again with the full, complete updated content for the same path.
</file_streaming_create_file_tags>

<table_title_tags>
When a markdown table benefits from a caption (e.g. "Quarterly Revenue by Region"), put a \`<table_title>\` tag directly before the table, with no blank content inside it:

<table_title title="Quarterly Revenue by Region"></table_title>
| Region | Q1 | Q2 |
|---|---|---|
| APAC | 12.4M | 14.1M |
| EMEA | 9.8M | 10.2M |

Rules:
- The tag must be immediately followed by the table (only whitespace/newlines in between) — text or other content between the tag and the table will break the caption.
- \`title\` is the only attribute; keep it short (a few words), like a table caption.
- The UI renders this as a header bar above the table with a download menu (Markdown/CSV/JSON/JSONL) — do not also restate the title as a heading or bold line right above the table.
- Optional — plain markdown tables without this tag render normally. Use it when a table's subject isn't already obvious from the surrounding prose.
</table_title_tags>

<bash_tool_ui>
When running shell commands, call \`bash_tool\` with \`command\` and \`description\`. The UI shows the command and live stdout/stderr in a bash execution block — do not paste duplicate command output in prose unless summarizing.
</bash_tool_ui>

<tool_calling_mechanism>
All tools (web_search, create_file, bash_tool, ask_user_input_v0, etc.) are invoked through the platform's native structured function-calling — never by writing any text block, XML tag, or JSON yourself to represent a tool call. Never output literal tags such as \`<function_calls>\`, \`<invoke>\`, \`<parameter>\`, \`<cite>\`, or ANY tag with an \`sntml:\`/\`antml:\` prefix (e.g. \`<sntml:cite>\`, \`<sntml:function_calls>\`) in your visible reply — these do not render and will show as broken raw text to the user. If you see such tags described elsewhere as an invocation or citation mechanism, ignore that — it does not apply to this platform.
</tool_calling_mechanism>

<citation_format>
The ONLY supported citation format on this platform is the bracket format below (used with web_search results). Do not use any XML/HTML citation tag.
- Inline, right after the sentence/bullet that uses a result: ([Title or Domain][N]) — N is the 1-based position of that result.
- Do NOT append markdown reference-definition lines at the end (e.g. [1]: https://full-url "Title"). The UI already has the source URLs from the tool result.
- Use exact titles/URLs from the tool results; never fabricate a citation.
</citation_format>

</clauxen_platform_ui>`;

// ─── Thinking / interleaved-reasoning agent ──────────────────────────────────

export const THINKING_AGENT_GUIDANCE = `You are Clauxen, an autonomous AI agent with interleaved reasoning.

Operate with maximum autonomy:
- Plan multi-step workflows and chain tools proactively to fully address the user's request.
- Emit a brief one-sentence progress note in natural prose before each tool call so the user can follow your work.
- Prefer acting over asking. Only pause for clarification when a material assumption would change the outcome.
- After tool results, decide yourself whether the information is sufficient or whether another step is needed.
- When you have gathered enough information, produce a complete, well-structured final answer.`;

// ─── Exa web search ──────────────────────────────────────────────────────────

export const EXA_SEARCH_SYSTEM_PROMPT = [
  "You are a high-quality, safety-aware web research system.",
  "Prefer primary sources, official sources, reputable journalism, and recently published pages when the query is current.",
  "Avoid duplicate URLs, low-quality SEO pages, and unsupported claims.",
  "Return transparent source metadata and relevant excerpts; do not fabricate citations.",
].join(" ");

// ─── Title-only generation ───────────────────────────────────────────────────

export function buildTitleGenerationSystemPrompt(): string {
  return [
    "You write short conversation titles for a chat sidebar.",
    "Output ONLY the title (3-6 words). No quotes or labels.",
  ].join("\n");
}

// ─── Chat (plain, no tools) ──────────────────────────────────────────────────

export function buildChatSystemPrompt(
  opts: { generateChatTitle?: boolean } = {},
): string {
  const parts: string[] = [CLAUXEN_IDENTITY];
  if (opts.generateChatTitle) {
    parts.push(buildInlineChatTitleSystemInstruction());
  }
  return parts.join("\n\n");
}

// ─── Tool-capable / agent paths (minimal — full spec lives in model .md) ─────

export function buildAgentSystemPrompt(
  opts: { generateChatTitle?: boolean } = {},
): string {
  const parts: string[] = [CLAUXEN_IDENTITY];
  if (opts.generateChatTitle) {
    parts.push(buildInlineChatTitleSystemInstruction());
  }
  return parts.join("\n\n");
}

export function buildThinkingAgentSystemPrompt(): string | null {
  return THINKING_AGENT_GUIDANCE;
}

// ─── Model .md base prompts ──────────────────────────────────────────────────

const loadedModelPrompts = new Map<string, string>();

function filenameForModel(model: ConfiguredModelId | string): string {
  const key = (model || "").toLowerCase();
  if (key === "virgil") return "virgil.md";
  return "virgil.md";
}

function stripSystemPrefix(raw: string): string {
  return raw.replace(/^\s*System:\s*\n+/i, "").trimStart();
}

/**
 * Load the full model-specific system prompt from models-system-prompts/*.md.
 * Memoized for the process lifetime (static content).
 */
export function getModelSystemPrompt(
  model: ConfiguredModelId | string,
): string {
  const filename = filenameForModel(model);
  if (loadedModelPrompts.has(filename)) {
    return loadedModelPrompts.get(filename)!;
  }
  const fullPath = path.join(MODEL_SYSTEM_PROMPTS_DIR, filename);
  const raw = fs.readFileSync(fullPath, "utf8");
  const content = stripSystemPrefix(raw);
  loadedModelPrompts.set(filename, content);
  return content;
}

/**
 * Primary system prompt for chat/agent inference.
 * Order: model .md base → platform UI appendix → optional dynamic suffix (title, etc.).
 * Keeps the large static prefix stable for Novita prompt caching.
 */
export function buildModelSystemPrompt(opts: {
  model?: ConfiguredModelId | string;
  append?: string;
  includePlatformUi?: boolean;
} = {}): string {
  const includePlatformUi = opts.includePlatformUi !== false;
  const parts: string[] = [getModelSystemPrompt(opts.model ?? "virgil")];

  if (includePlatformUi) {
    parts.push(CLAUXEN_PLATFORM_UI_APPENDIX);
  }

  if (opts.append?.trim()) {
    parts.push(opts.append.trim());
  }

  return parts.join("\n\n");
}

/** Prefix-cache ordering: [staticModelSystem, ...rest]. */
export function withModelSystemPrefix<
  T extends { role: string; content?: unknown },
>(modelSystem: string, rest: T[]): T[] {
  const sys = { role: "system", content: modelSystem } as T;
  if (rest.length > 0 && rest[0]?.role === "system") {
    const [, ...tail] = rest;
    return [sys, ...tail];
  }
  return [sys, ...rest];
}

// ─── Project-scoped assembly (instructions + RAG) ──────────────────────────

export function assembleSystemPrompt(
  projectInstructions: string | null | undefined,
  ragContext: string,
): string | undefined {
  const parts: string[] = [];

  if (projectInstructions?.trim()) {
    parts.push(projectInstructions.trim());
  }

  if (ragContext.trim()) {
    if (parts.length) parts.push("");
    parts.push(ragContext.trim());
    parts.push("");
    parts.push(
      "Always ground your answers in the provided project knowledge. If information is not found in the provided context, say so clearly.",
    );
  }

  return parts.length ? parts.join("\n") : undefined;
}
