-- =============================================================================
-- CockroachDB Cloud — manual SQL upload (Postgres integer semantics)
-- Unqualified INT / INTEGER in this session resolve to INT4 (like PostgreSQL).
-- Apply cockroachdb/bootstrap/crdb_supabase_shim.sql once before the first migration.
-- Generated by: node cockroachdb/scripts/prepare-crdb-upload-sql.mjs
-- =============================================================================
SET default_int_size = 4;


-- =============================================================================
-- Migration: 20260507200000_security_advisor_hardening
-- Purpose: Address Supabase Security Advisor findings by pinning function
--          search_path, moving vector into extensions schema, and restricting
--          SECURITY DEFINER RPCs to service_role only.
-- Prerequisites:
--   - public.* functions listed below already exist.
--   - extensions schema creatable (Supabase pattern).
-- Apply-time behavior:
--   - Creates extensions schema; sets search_path on helper/trigger functions.
--   - Moves pgvector extension to extensions schema when present.
--   - Revokes EXECUTE from public/anon/authenticated on sensitive RPCs;
--     grants EXECUTE to service_role only (two signature batches).
-- Security / RLS:
--   - No table RLS changes. Reduces search_path hijack risk on SECURITY
--     DEFINER functions and prevents direct client invocation of billing/chat
--     RPCs via PostgREST.
-- Rollback guidance:
--   - Re-grant EXECUTE to authenticated where intentionally exposed (avoid).
--   - ALTER EXTENSION vector SET SCHEMA public only if required by tooling.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Schema: extensions (isolated extension objects)
-- -----------------------------------------------------------------------------
create schema if not exists extensions;

-- -----------------------------------------------------------------------------
-- search_path hardening on trigger/helper functions
-- Prevents malicious objects in public from shadowing builtins/extensions.
-- -----------------------------------------------------------------------------
-- omitted on CRDB: ALTER FUNCTION ... SET search_path


-- omitted on CRDB: ALTER FUNCTION ... SET search_path


-- omitted on CRDB: ALTER FUNCTION ... SET search_path


-- omitted on CRDB: ALTER FUNCTION ... SET search_path


-- omitted on CRDB: ALTER FUNCTION ... SET search_path


-- -----------------------------------------------------------------------------
-- Extension placement: vector in extensions schema
-- -----------------------------------------------------------------------------
do $$
begin
  alter extension vector set schema extensions;
exception
  when undefined_object then null;
end $$;

-- -----------------------------------------------------------------------------
-- RPC lockdown batch 1: application SECURITY DEFINER functions
-- Revoke from API roles; backend uses service_role key for these calls.
-- -----------------------------------------------------------------------------
do $$
declare
  v_signature text;
  v_signatures text[] := array[
    'public.append_chat_message(uuid,text,text,jsonb,uuid,uuid,text,integer,integer)',
    'public.bootstrap_existing_auth_users()',
    'public.create_chat(text,uuid,uuid,text)',
    'public.create_default_workspace_for_user(uuid,text,text)',
    'public.create_storage_object_record(text,text,text,text,jsonb)',
    'public.credit_user_tokens(uuid,integer,text,text,jsonb)',
    'public.debit_user_tokens(uuid,integer,text,text,jsonb)',
    'public.expire_old_gift_codes()',
    'public.fulfill_billing_payment(text,text,text,text,text,text,timestamp with time zone,text,text,text,integer,text,jsonb)',
    'public.get_recent_chats(integer,integer)',
    'public.handle_new_user()',
    'public.increment_numeric_field(text,text,text,integer)',
    'public.is_workspace_member(uuid)',
    'public.is_workspace_owner(uuid)',
    'public.match_document_chunks(VECTOR(1536), integer, jsonb)',
    'public.queue_file_processing_job(uuid,text)',
    'public.queue_gift_delivery(uuid)',
    'public.record_model_usage(uuid,uuid,uuid,uuid,text,text,integer,integer,integer,jsonb)',
    'public.redeem_gift_code(text)',
    'public.rollup_model_usage(timestamp with time zone,timestamp with time zone)',
    'public.search_user_messages(text,integer)'
  ];
begin
  foreach v_signature in array v_signatures loop
    execute format('revoke all on function %s from public', v_signature);
    execute format('revoke all on function %s from anon', v_signature);
    execute format('revoke all on function %s from authenticated', v_signature);
    execute format('grant execute on function %s to service_role', v_signature);
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- RPC lockdown batch 2: internal trigger/helper functions
-- -----------------------------------------------------------------------------
do $$
declare
  v_signature text;
  v_signatures text[] := array[
    'public.ensure_updated_at_trigger(regclass)',
    'public.current_profile_id()',
    'public.set_updated_at()',
    'public.hash_gift_code(text)',
    'public.generate_gift_code()'
  ];
begin
  foreach v_signature in array v_signatures loop
    execute format('revoke all on function %s from public', v_signature);
    execute format('revoke all on function %s from anon', v_signature);
    execute format('revoke all on function %s from authenticated', v_signature);
    execute format('grant execute on function %s to service_role', v_signature);
  end loop;
end $$;
