-- =============================================================================
-- CockroachDB Cloud — manual SQL upload (Postgres integer semantics)
-- Unqualified INT / INTEGER in this session resolve to INT4 (like PostgreSQL).
-- Apply cockroachdb/bootstrap/crdb_supabase_shim.sql once before the first migration.
-- Generated by: node cockroachdb/scripts/prepare-crdb-upload-sql.mjs
-- =============================================================================
SET default_int_size = 4;


-- =============================================================================
-- Migration: model_training_priority_governance_expansion
-- =============================================================================
--
-- Purpose
--   Expand the control plane for (1) model-training consent and eligibility,
--   (2) provider priority / queue semantics during peak load, and (3) org-level
--   governance, audit, and operational telemetry. This migration is additive:
--   new columns are nullable or carry safe defaults so existing application
--   reads and writes continue to work without a coordinated deploy.
--
-- Scope (high level)
--   • Training opt-in: profile defaults, per-user settings, workspace policy,
--     append-only consent events, and training flags on usage/memory rows.
--   • Priority queues: plan/subscription snapshots, rate-limit queue fields,
--     router rules, runtime priority snapshots, capacity windows, Nomita routing.
--   • Governance: compliance tiers, DPA/legal-hold, data classification, audit
--     enrichment, moderation training blocks, feature-flag rollout metadata.
--   • New tables: model_training_consent_events, model_usage_realtime_windows,
--     model_priority_runtime_snapshots, provider_capacity_windows.
--   • RLS + grants: user-readable consent/snapshots; internal ops tables locked
--     down; service_role and optional dashboard/read-only role grants.
--
-- Dependencies
--   Assumes core platform tables from earlier migrations (profiles, workspaces,
--   plans, subscriptions, model_catalog, model_router_rules, etc.).
--
-- Rollout notes
--   • Plan priority semantics are seeded at the end; re-run safe via UPDATE … WHERE.
--   • Realtime publication for model_usage_realtime_windows is best-effort (duplicate
--     publication errors are swallowed).
--   • Ends with `-- omitted on CRDB: NOTIFY pgrst (PostgREST)


-- user_settings — per-user training consent, modalities, and evidence capture
alter table public.user_settings
  add column if not exists data_training_opt_out_reason text,
  add column if not exists data_training_scope text not null default 'none',
  add column if not exists data_training_allowed_modalities text[] not null default '{}'::text[],
  add column if not exists data_training_blocked_categories text[] not null default '{}'::text[],
  add column if not exists data_retention_preference text not null default 'standard',
  add column if not exists personalization_training_enabled boolean not null default false,
  add column if not exists product_analytics_opt_in boolean not null default false,
  add column if not exists research_contact_opt_in boolean not null default false,
  -- Consent provenance for regulatory requests (version, timestamp, IP, UA, evidence blob)
  add column if not exists consent_policy_version text,
  add column if not exists consent_captured_at timestamptz,
  add column if not exists consent_captured_ip inet,
  add column if not exists consent_captured_user_agent text,
  add column if not exists consent_evidence jsonb not null default '{}'::jsonb,
  add column if not exists privacy_review_required boolean not null default false,
  add column if not exists privacy_review_reason text,
  add column if not exists training_data_boundary jsonb not null default '{}'::jsonb;

-- workspaces — org-level compliance, residency, and default training policy
alter table public.workspaces
  add column if not exists organization_type text not null default 'personal',
  add column if not exists enterprise_account_id text,
  add column if not exists billing_entity_name text,
  add column if not exists compliance_tier text not null default 'standard',
  add column if not exists data_residency_region text,
  add column if not exists support_tier text not null default 'standard',
  add column if not exists priority_tier text not null default 'standard',
  add column if not exists peak_priority_boost integer not null default 0,
  add column if not exists training_default_opt_in boolean not null default false,
  add column if not exists training_policy text not null default 'user_controlled',
  add column if not exists contractual_training_restrictions jsonb not null default '{}'::jsonb,
  add column if not exists dpa_signed_at timestamptz,
  add column if not exists security_review_status text not null default 'not_started',
  add column if not exists admin_notes text;

-- workspace_settings — enforceable workspace training controls and governance JSON
alter table public.workspace_settings
  add column if not exists workspace_training_opt_in boolean not null default false,
  add column if not exists training_allowed_modalities text[] not null default '{}'::text[],
  add column if not exists training_blocked_categories text[] not null default '{}'::text[],
  -- When true, enterprise admins block per-user opt-in overrides
  add column if not exists enterprise_training_lock boolean not null default false,
  add column if not exists training_policy_version text,
  add column if not exists data_classification_default text not null default 'internal',
  add column if not exists pii_handling_policy text not null default 'redact',
  add column if not exists retention_policy_days integer,
  add column if not exists legal_hold_enabled boolean not null default false,
  add column if not exists audit_export_enabled boolean not null default false,
  add column if not exists peak_priority_policy text not null default 'plan_based',
  add column if not exists peak_priority_floor integer not null default 0,
  add column if not exists peak_priority_ceiling integer not null default 100,
  add column if not exists dedicated_capacity_pool text,
  add column if not exists nomita_workspace_routing jsonb not null default '{}'::jsonb,
  add column if not exists realtime_usage_visibility text not null default 'admins_only',
  add column if not exists model_governance jsonb not null default '{}'::jsonb,
  add column if not exists last_governance_review_at timestamptz;


-- =============================================================================
-- SECTION: Priority queues and entitlements (plans, billing, usage)
-- =============================================================================
-- Wires subscription-tier priority into plans, live subscription snapshots,
-- token accounting, and daily rollups. priority_rank is numeric (higher = sooner
-- in queue). highest_priority_* flags gate Nomita “jump the queue” behavior;
-- plus_highest_priority_blocked prevents Plus from claiming highest tier.

-- plans — canonical priority / peak / training entitlements per SKU
alter table public.plans
  add column if not exists service_level text not null default 'standard',
  add column if not exists priority_rank integer not null default 10,
  add column if not exists highest_priority_eligible boolean not null default false,
  add column if not exists peak_priority_weight numeric(8,4) not null default 1.0000,
  add column if not exists dedicated_capacity_eligible boolean not null default false,
  add column if not exists burst_multiplier numeric(8,4) not null default 1.0000,
  add column if not exists soft_limit_multiplier numeric(8,4) not null default 1.0000,
  add column if not exists queue_jump_allowed boolean not null default false,
  add column if not exists plus_highest_priority_blocked boolean not null default false,
  add column if not exists training_default_opt_in_allowed boolean not null default false,
  add column if not exists enterprise_controls_enabled boolean not null default false,
  add column if not exists business_controls_enabled boolean not null default false,
  add column if not exists support_response_sla_minutes integer,
  add column if not exists model_access_policy jsonb not null default '{}'::jsonb,
  add column if not exists rate_limit_policy jsonb not null default '{}'::jsonb,
  add column if not exists peak_time_policy jsonb not null default '{}'::jsonb,
  add column if not exists training_policy jsonb not null default '{}'::jsonb,
  add column if not exists governance_notes text,
  add column if not exists effective_from timestamptz not null default now();

-- subscriptions — point-in-time snapshots copied from plan at recalc time
alter table public.subscriptions
  add column if not exists service_level_snapshot text,
  add column if not exists priority_rank_snapshot integer,
  add column if not exists highest_priority_active boolean not null default false,
  add column if not exists peak_priority_weight_snapshot numeric(8,4),
  add column if not exists capacity_pool text,
  add column if not exists throttling_policy text not null default 'standard',
  add column if not exists burst_credits_remaining integer,
  add column if not exists peak_usage_window_started_at timestamptz,
  add column if not exists last_priority_recalculated_at timestamptz,
  add column if not exists training_entitlement_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists enterprise_contract_id text,
  add column if not exists business_unit text,
  add column if not exists seat_count integer,
  add column if not exists admin_contact_email text,
  add column if not exists provider_contract_metadata jsonb not null default '{}'::jsonb,
  add column if not exists nomita_priority_group text,
  add column if not exists nomita_routing_metadata jsonb not null default '{}'::jsonb,
  add column if not exists entitlement_notes text;

-- user_balances — reserved/pending splits for priority billing under load
alter table public.user_balances
  add column if not exists reserved_tokens integer not null default 0,
  add column if not exists pending_debits integer not null default 0,
  add column if not exists monthly_grant_tokens integer not null default 0,
  add column if not exists rollover_tokens integer not null default 0,
  add column if not exists promotional_tokens integer not null default 0,
  add column if not exists enterprise_pool_tokens integer not null default 0,
  add column if not exists last_grant_at timestamptz,
  add column if not exists last_debit_at timestamptz,
  add column if not exists balance_policy jsonb not null default '{}'::jsonb,
  add column if not exists balance_audit_metadata jsonb not null default '{}'::jsonb;

-- token_transactions — per-request priority and settlement trace for disputes
alter table public.token_transactions
  add column if not exists request_id text,
  add column if not exists idempotency_key text,
  add column if not exists priority_rank integer,
  add column if not exists service_level text,
  add column if not exists model_provider text,
  add column if not exists model_id text,
  add column if not exists reservation_id text,
  add column if not exists balance_before integer,
  add column if not exists balance_after integer,
  add column if not exists peak_window_id uuid,
  add column if not exists billing_context jsonb not null default '{}'::jsonb,
  add column if not exists settlement_metadata jsonb not null default '{}'::jsonb;

-- usage_daily_rollups — aggregated peak/throttle/training counters per day
alter table public.usage_daily_rollups
  add column if not exists service_level text,
  add column if not exists priority_rank integer,
  add column if not exists provider text,
  add column if not exists model_family text,
  add column if not exists peak_requests integer not null default 0,
  add column if not exists throttled_requests integer not null default 0,
  add column if not exists training_eligible_events integer not null default 0,
  add column if not exists training_blocked_events integer not null default 0,
  add column if not exists average_latency_ms numeric(12,2),
  add column if not exists p95_latency_ms numeric(12,2),
  add column if not exists provider_cost_amount numeric(18,8),
  add column if not exists rollup_metadata jsonb not null default '{}'::jsonb;


-- =============================================================================
-- SECTION: Model routing, rate limits, and per-request telemetry
-- =============================================================================
-- Extends the inference control plane: catalog capabilities, router rules that
-- match on priority band and peak windows, live provider health, per-tenant rate
-- limits with queue position, and rich model_usage_events rows for analytics.

alter table public.model_catalog
  add column if not exists provider_display_name text,
  add column if not exists model_family text,
  add column if not exists model_version text,
  add column if not exists context_window_tokens integer,
  add column if not exists max_output_tokens integer,
  add column if not exists default_temperature numeric(5,3),
  add column if not exists supports_streaming boolean not null default true,
  add column if not exists supports_tools boolean not null default false,
  add column if not exists supports_vision boolean not null default false,
  add column if not exists supports_audio boolean not null default false,
  add column if not exists supports_embeddings boolean not null default false,
  add column if not exists supports_realtime boolean not null default false,
  add column if not exists training_data_policy text not null default 'not_applicable',
  add column if not exists retention_policy text not null default 'provider_default',
  add column if not exists data_residency_regions text[] not null default '{}'::text[],
  add column if not exists fallback_model_ids text[] not null default '{}'::text[],
  add column if not exists priority_supported boolean not null default false,
  add column if not exists peak_capacity_units integer,
  add column if not exists nomita_model_slug text,
  add column if not exists nomita_routing_metadata jsonb not null default '{}'::jsonb;

-- model_router_rules — matches requests to models by priority band and plan
alter table public.model_router_rules
  add column if not exists service_level text,
  add column if not exists priority_rank_min integer,
  add column if not exists priority_rank_max integer,
  add column if not exists peak_only boolean not null default false,
  add column if not exists training_allowed boolean,
  add column if not exists data_classification_allowed text[] not null default '{}'::text[],
  add column if not exists allowed_plan_ids text[] not null default '{}'::text[],
  add column if not exists blocked_plan_ids text[] not null default '{}'::text[],
  add column if not exists highest_priority_required boolean not null default false,
  add column if not exists plus_highest_priority_blocked boolean not null default true,
  add column if not exists enterprise_override_allowed boolean not null default true,
  add column if not exists provider_weight numeric(8,4) not null default 1.0000,
  add column if not exists failover_order jsonb not null default '[]'::jsonb,
  add column if not exists max_queue_depth integer,
  add column if not exists max_latency_ms integer,
  add column if not exists capacity_pool text,
  add column if not exists nomita_route_key text,
  add column if not exists nomita_policy jsonb not null default '{}'::jsonb,
  add column if not exists evaluation_tags text[] not null default '{}'::text[],
  add column if not exists rollout_percentage numeric(5,2) not null default 100.00,
  add column if not exists starts_at timestamptz,
  add column if not exists ends_at timestamptz;

-- provider_health_checks — saturation and circuit state for capacity routing
alter table public.provider_health_checks
  add column if not exists region text,
  add column if not exists capacity_pool text,
  add column if not exists observed_qps numeric(12,4),
  add column if not exists max_qps numeric(12,4),
  add column if not exists queue_depth integer,
  add column if not exists saturation_ratio numeric(8,4),
  add column if not exists p50_latency_ms integer,
  add column if not exists p95_latency_ms integer,
  add column if not exists p99_latency_ms integer,
  add column if not exists error_rate numeric(8,4),
  add column if not exists throttle_rate numeric(8,4),
  add column if not exists circuit_state text not null default 'closed',
  add column if not exists last_success_at timestamptz,
  add column if not exists last_failure_at timestamptz,
  add column if not exists degraded_reason text,
  add column if not exists nomita_status_payload jsonb not null default '{}'::jsonb,
  add column if not exists recommended_action text,
  add column if not exists expires_at timestamptz;

-- rate_limits — token bucket + concurrency + queue position per subject/window
alter table public.rate_limits
  add column if not exists plan_id text,
  add column if not exists service_level text,
  add column if not exists priority_rank integer not null default 10,
  add column if not exists highest_priority boolean not null default false,
  add column if not exists burst_limit integer,
  add column if not exists sustained_limit integer,
  add column if not exists refill_rate numeric(12,4),
  add column if not exists tokens_remaining numeric(18,4),
  add column if not exists concurrency_limit integer,
  add column if not exists concurrency_in_use integer not null default 0,
  add column if not exists queue_position integer,
  add column if not exists queue_entered_at timestamptz,
  add column if not exists peak_window boolean not null default false,
  add column if not exists throttle_reason text,
  add column if not exists provider text,
  add column if not exists model_id text,
  add column if not exists workspace_id uuid,
  add column if not exists user_id uuid,
  add column if not exists enforcement_metadata jsonb not null default '{}'::jsonb,
  add column if not exists last_enforced_at timestamptz;

-- model_usage_events — one row per inference; queue wait and training snapshot
alter table public.model_usage_events
  add column if not exists request_id text,
  add column if not exists session_id text,
  add column if not exists route_rule_id uuid,
  add column if not exists provider_request_id text,
  add column if not exists provider_region text,
  add column if not exists provider_cluster text,
  add column if not exists capacity_pool text,
  add column if not exists service_level text,
  add column if not exists plan_id text,
  add column if not exists priority_rank integer,
  add column if not exists highest_priority boolean not null default false,
  add column if not exists peak_window boolean not null default false,
  add column if not exists queue_entered_at timestamptz,
  add column if not exists queue_released_at timestamptz,
  add column if not exists queue_wait_ms integer,
  add column if not exists time_to_first_token_ms integer,
  add column if not exists provider_latency_ms integer,
  add column if not exists retry_count integer not null default 0,
  add column if not exists fallback_count integer not null default 0,
  add column if not exists fallback_chain jsonb not null default '[]'::jsonb,
  add column if not exists throttle_applied boolean not null default false,
  add column if not exists throttle_reason text,
  add column if not exists request_status text not null default 'completed',
  add column if not exists error_code text,
  add column if not exists error_message text,
  add column if not exists training_eligible boolean not null default false,
  add column if not exists training_consent_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists data_classification text not null default 'user_content',
  add column if not exists prompt_hash text,
  add column if not exists response_hash text,
  add column if not exists safety_policy_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists nomita_request_id text,
  add column if not exists nomita_routing_metadata jsonb not null default '{}'::jsonb,
  add column if not exists billing_trace jsonb not null default '{}'::jsonb;


-- =============================================================================
-- SECTION: Governance, security, audit, and memory training flags
-- =============================================================================
-- Cross-cutting controls: feature-flag rollout risk, API key policy caps,
-- richer audit/moderation trails, and per-memory training eligibility with
-- consent snapshots for downstream dataset pipelines.

alter table public.feature_flags
  add column if not exists owner_team text,
  add column if not exists risk_level text not null default 'low',
  add column if not exists affects_model_routing boolean not null default false,
  add column if not exists affects_training boolean not null default false,
  add column if not exists allowed_plan_ids text[] not null default '{}'::text[],
  add column if not exists blocked_plan_ids text[] not null default '{}'::text[],
  add column if not exists audit_required boolean not null default false,
  add column if not exists rollout_started_at timestamptz,
  add column if not exists rollout_ended_at timestamptz,
  add column if not exists evaluation_metadata jsonb not null default '{}'::jsonb;

alter table public.api_keys
  add column if not exists key_type text not null default 'user',
  add column if not exists environment text not null default 'production',
  add column if not exists allowed_providers text[] not null default '{}'::text[],
  add column if not exists allowed_models text[] not null default '{}'::text[],
  add column if not exists max_priority_rank integer,
  add column if not exists training_access_allowed boolean not null default false,
  add column if not exists last_used_ip inet,
  add column if not exists last_used_user_agent text,
  add column if not exists rotation_required_at timestamptz,
  add column if not exists revoked_reason text,
  add column if not exists policy_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists usage_metadata jsonb not null default '{}'::jsonb;

alter table public.audit_logs
  add column if not exists request_id text,
  add column if not exists session_id text,
  add column if not exists actor_email text,
  add column if not exists actor_plan_id text,
  add column if not exists actor_service_level text,
  add column if not exists risk_level text not null default 'low',
  add column if not exists compliance_tags text[] not null default '{}'::text[],
  add column if not exists data_classification text,
  add column if not exists before_state jsonb,
  add column if not exists after_state jsonb,
  add column if not exists decision_trace jsonb not null default '{}'::jsonb,
  add column if not exists retention_expires_at timestamptz;

alter table public.moderation_events
  add column if not exists provider_request_id text,
  add column if not exists model_id text,
  add column if not exists policy_version text,
  add column if not exists category_scores jsonb not null default '{}'::jsonb,
  add column if not exists redaction_applied boolean not null default false,
  add column if not exists training_blocked boolean not null default true,
  add column if not exists escalation_required boolean not null default false,
  add column if not exists reviewer_id uuid,
  add column if not exists reviewed_at timestamptz,
  add column if not exists appeal_status text,
  add column if not exists decision_latency_ms integer,
  add column if not exists jurisdiction text,
  add column if not exists retention_expires_at timestamptz,
  add column if not exists audit_trace jsonb not null default '{}'::jsonb;

alter table public.user_memories
  add column if not exists training_eligible boolean not null default false,
  add column if not exists training_block_reason text,
  add column if not exists data_classification text not null default 'personal',
  add column if not exists pii_detected boolean not null default false,
  add column if not exists consent_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists retention_expires_at timestamptz,
  add column if not exists source_model_id text,
  add column if not exists extraction_policy_version text,
  add column if not exists quality_score numeric(8,4),
  add column if not exists review_metadata jsonb not null default '{}'::jsonb;

alter table public.memory_events
  add column if not exists actor_type text not null default 'system',
  add column if not exists actor_id uuid,
  add column if not exists training_state_before text,
  add column if not exists training_state_after text,
  add column if not exists consent_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists policy_version text,
  add column if not exists event_reason text,
  add column if not exists request_id text,
  add column if not exists data_classification text,
  add column if not exists audit_trace jsonb not null default '{}'::jsonb;


-- =============================================================================
-- SECTION: Governance tables (append-only / operational control plane)
-- =============================================================================
-- New first-class tables for consent history, realtime usage buckets, per-request
-- priority decisions, and provider capacity windows. Writes are expected from
-- edge workers / service_role; clients read only where RLS policies allow.

-- Immutable consent transitions (append-only; do not UPDATE rows in application code)
create table if not exists public.model_training_consent_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  subject_type text not null default 'user',
  subject_id text,
  plan_id text references public.plans(id),
  service_level text,
  consent_state text not null,
  consent_scope text not null default 'none',
  allowed_modalities text[] not null default '{}'::text[],
  blocked_categories text[] not null default '{}'::text[],
  data_classification text,
  policy_version text,
  source text not null default 'settings',
  source_ip inet,
  source_user_agent text,
  evidence jsonb not null default '{}'::jsonb,
  effective_at timestamptz not null default now(),
  expires_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

-- Rolling realtime aggregates per provider/model/plan window (feeds dashboards + realtime)
create table if not exists public.model_usage_realtime_windows (
  id uuid primary key default gen_random_uuid(),
  window_start timestamptz not null,
  window_end timestamptz not null,
  bucket_seconds integer not null default 60,
  provider text not null default 'nomita',
  model_id text,
  model_family text,
  region text,
  capacity_pool text,
  service_level text not null default 'standard',
  plan_id text references public.plans(id),
  priority_rank integer not null default 10,
  highest_priority boolean not null default false,
  active_requests integer not null default 0,
  queued_requests integer not null default 0,
  completed_requests integer not null default 0,
  failed_requests integer not null default 0,
  throttled_requests integer not null default 0,
  training_eligible_requests integer not null default 0,
  training_blocked_requests integer not null default 0,
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  cost_amount numeric(18,8),
  avg_latency_ms numeric(12,2),
  p95_latency_ms numeric(12,2),
  saturation_ratio numeric(8,4),
  queue_depth integer not null default 0,
  capacity_units integer,
  nomita_capacity_snapshot jsonb not null default '{}'::jsonb,
  routing_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Per-request priority routing decision log (debugging queue fairness disputes)
create table if not exists public.model_priority_runtime_snapshots (
  id uuid primary key default gen_random_uuid(),
  request_id text,
  user_id uuid references auth.users(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  subscription_id uuid references public.subscriptions(id) on delete set null,
  plan_id text references public.plans(id),
  service_level text not null default 'standard',
  priority_rank integer not null default 10,
  highest_priority boolean not null default false,
  plus_highest_priority_blocked boolean not null default true,
  peak_window boolean not null default false,
  provider text not null default 'nomita',
  model_id text,
  capacity_pool text,
  queue_position integer,
  queue_wait_ms integer,
  decision text not null default 'allow',
  decision_reason text,
  router_rule_id uuid references public.model_router_rules(id) on delete set null,
  entitlement_snapshot jsonb not null default '{}'::jsonb,
  rate_limit_snapshot jsonb not null default '{}'::jsonb,
  provider_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Provider-side capacity telemetry buckets (feeds autoscaling / throttle recommendations)
create table if not exists public.provider_capacity_windows (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'nomita',
  model_id text,
  model_family text,
  region text,
  capacity_pool text,
  window_start timestamptz not null,
  window_end timestamptz not null,
  max_qps numeric(12,4),
  observed_qps numeric(12,4),
  max_concurrency integer,
  observed_concurrency integer,
  queue_depth integer,
  saturation_ratio numeric(8,4),
  error_rate numeric(8,4),
  throttle_rate numeric(8,4),
  health_state text not null default 'unknown',
  recommended_priority_floor integer,
  recommended_throttle_policy text,
  nomita_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =============================================================================
-- SECTION: Row-level security (RLS)
-- =============================================================================
-- Enable RLS on all new tables. Users may SELECT their own consent events and
-- priority snapshots. Realtime/capacity windows are internal ops data — no
-- authenticated SELECT policies (service_role / dashboard roles only).

alter table public.model_training_consent_events enable row level security;

alter table public.model_usage_realtime_windows enable row level security;

alter table public.model_priority_runtime_snapshots enable row level security;

alter table public.provider_capacity_windows enable row level security;

drop policy if exists "Users can read own training consent events" on public.model_training_consent_events;

create policy "Users can read own training consent events"
on public.model_training_consent_events
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Users can read own priority snapshots" on public.model_priority_runtime_snapshots;

create policy "Users can read own priority snapshots"
on public.model_priority_runtime_snapshots
for select
to authenticated
using (user_id = (select auth.uid()));

-- model_usage_realtime_windows and provider_capacity_windows: RLS enabled, no
-- client-facing policies — operational telemetry visible via service_role /
-- dashboard_user / supabase_read_only_user grants below.


-- =============================================================================
-- SECTION: Seed plan priority semantics
-- =============================================================================
-- Materializes priority_rank, service_level, and JSON policy blobs on known SKUs.
-- Plus is explicitly non-highest (plus_highest_priority_blocked). Max/Team/Business
-- tiers that already expose highest_priority in product are marked eligible.
-- training_default_opt_in_allowed is false for all seeded plans (explicit consent).

update public.plans
set
  service_level = case
    when id in ('enterprise') then 'enterprise'
    when id in ('team', 'business', 'max', 'max5x', 'max20x') then 'business'
    when id in ('pro') then 'pro'
    when id in ('plus') then 'plus'
    when id in ('go') then 'go'
    else 'free'
  end,
  priority_rank = case
    when id in ('enterprise') then 100
    when id in ('team', 'business', 'max20x') then 95
    when id in ('max', 'max5x') then 90
    when id in ('pro') then 80
    when id in ('plus') then 40
    when id in ('go') then 20
    else 10
  end,
  highest_priority_eligible = id in ('enterprise', 'team', 'business', 'max', 'max5x', 'max20x', 'pro'),
  plus_highest_priority_blocked = id in ('plus'),
  dedicated_capacity_eligible = id in ('enterprise', 'team', 'business', 'max20x'),
  queue_jump_allowed = id in ('enterprise', 'team', 'business', 'max', 'max5x', 'max20x', 'pro'),
  enterprise_controls_enabled = id in ('enterprise'),
  business_controls_enabled = id in ('enterprise', 'team', 'business', 'max', 'max5x', 'max20x'),
  training_default_opt_in_allowed = id in ('enterprise', 'team', 'business') and false,
  peak_priority_weight = case
    when id in ('enterprise') then 4.0000
    when id in ('team', 'business', 'max20x') then 3.5000
    when id in ('max', 'max5x') then 3.0000
    when id in ('pro') then 2.2500
    when id in ('plus') then 1.2500
    when id in ('go') then 1.1000
    else 1.0000
  end,
  peak_time_policy = coalesce(peak_time_policy, '{}'::jsonb) ||
    jsonb_build_object(
      'highestPriorityOnlyFor', array['pro', 'business', 'enterprise'],
      'plusHighestPriorityBlocked', true,
      'provider', 'nomita'
    ),
  rate_limit_policy = coalesce(rate_limit_policy, '{}'::jsonb) ||
    jsonb_build_object(
      'priorityRank', case
        when id in ('enterprise') then 100
        when id in ('team', 'business', 'max20x') then 95
        when id in ('max', 'max5x') then 90
        when id in ('pro') then 80
        when id in ('plus') then 40
        when id in ('go') then 20
        else 10
      end
    ),
  training_policy = coalesce(training_policy, '{}'::jsonb) ||
    jsonb_build_object(
      'defaultOptIn', false,
      'requiresExplicitUserConsent', true,
      'enterpriseMayDisableOrgWide', true
    )
where id in ('free', 'go', 'plus', 'pro', 'max', 'max5x', 'max20x', 'team', 'business', 'enterprise');

-- Backfill subscription snapshots from current plan rows for active/trialing subs
update public.subscriptions s
set
  service_level_snapshot = p.service_level,
  priority_rank_snapshot = p.priority_rank,
  highest_priority_active = p.highest_priority_eligible and s.status in ('active', 'trialing'),
  peak_priority_weight_snapshot = p.peak_priority_weight,
  training_entitlement_snapshot = jsonb_build_object(
    'defaultOptIn', false,
    'requiresExplicitUserConsent', true,
    'planId', p.id,
    'serviceLevel', p.service_level
  ),
  nomita_priority_group = case
    when p.highest_priority_eligible and s.status in ('active', 'trialing') then p.service_level
    else 'standard'
  end,
  last_priority_recalculated_at = now()
from public.plans p
where s.plan_id = p.id;


-- =============================================================================
-- SECTION: Indexes (operational lookups; no blanket JSONB GIN)
-- =============================================================================
-- Targeted B-tree indexes on hot filter columns. Unique indexes on window tables
-- enforce idempotent upserts from edge aggregators.

create index if not exists profiles_training_consent_idx
on public.profiles (training_eligibility_default, training_consent_scope, updated_at desc);

create index if not exists user_settings_training_consent_idx
on public.user_settings (data_training_opt_in, data_training_scope, updated_at desc);

create index if not exists workspaces_priority_tier_idx
on public.workspaces (priority_tier, plan_id, updated_at desc);

create index if not exists subscriptions_priority_active_idx
on public.subscriptions (highest_priority_active, priority_rank_snapshot desc, current_period_end desc)
where status in ('active', 'trialing');

create index if not exists model_usage_events_priority_created_idx
on public.model_usage_events (provider, highest_priority, priority_rank desc, created_at desc);

create index if not exists model_usage_events_training_created_idx
on public.model_usage_events (training_eligible, created_at desc);

create index if not exists rate_limits_priority_window_idx
on public.rate_limits (provider, service_level, priority_rank desc, window_start);

create index if not exists model_router_rules_peak_priority_idx
on public.model_router_rules (is_enabled, peak_only, priority_rank_min, priority_rank_max, priority);

create index if not exists provider_health_capacity_checked_idx
on public.provider_health_checks (provider, capacity_pool, checked_at desc);

create index if not exists model_training_consent_events_user_created_idx
on public.model_training_consent_events (user_id, created_at desc);

create index if not exists model_training_consent_events_workspace_created_idx
on public.model_training_consent_events (workspace_id, created_at desc);

create index if not exists model_usage_realtime_windows_lookup_idx
on public.model_usage_realtime_windows (window_start desc, provider, service_level, priority_rank desc);

create unique index if not exists model_usage_realtime_windows_unique_idx
on public.model_usage_realtime_windows (
  window_start,
  provider,
  coalesce(model_id, ''),
  coalesce(region, ''),
  coalesce(capacity_pool, ''),
  service_level,
  coalesce(plan_id, '')
);

create index if not exists model_priority_snapshots_request_idx
on public.model_priority_runtime_snapshots (request_id)
where request_id is not null;

create index if not exists model_priority_snapshots_user_created_idx
on public.model_priority_runtime_snapshots (user_id, created_at desc);

create index if not exists provider_capacity_windows_lookup_idx
on public.provider_capacity_windows (provider, window_start desc, capacity_pool);

create unique index if not exists provider_capacity_windows_unique_idx
on public.provider_capacity_windows (
  provider,
  coalesce(model_id, ''),
  coalesce(region, ''),
  coalesce(capacity_pool, ''),
  window_start
);


-- =============================================================================
-- SECTION: Realtime publication, grants, schema reload
-- =============================================================================

-- Expose realtime windows to Supabase Realtime subscribers (dashboards, internal tools)
do $$
begin
-- omitted on CRDB: supabase_realtime

exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

-- authenticated: read own consent history and priority decision logs only
grant select on table
  public.model_training_consent_events,
  public.model_priority_runtime_snapshots
to authenticated;

-- service_role: full CRUD on all new control-plane tables (edge workers, cron)
grant all privileges on table
  public.model_training_consent_events,
  public.model_usage_realtime_windows,
  public.model_priority_runtime_snapshots,
  public.provider_capacity_windows
to service_role;

-- Optional Supabase Studio / read-replica roles when present in the project
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'dashboard_user') then
    execute 'grant all privileges on table public.model_training_consent_events to dashboard_user';
    execute 'grant all privileges on table public.model_usage_realtime_windows to dashboard_user';
    execute 'grant all privileges on table public.model_priority_runtime_snapshots to dashboard_user';
    execute 'grant all privileges on table public.provider_capacity_windows to dashboard_user';
  end if;

  if exists (select 1 from pg_roles where rolname = 'supabase_read_only_user') then
    execute 'grant select on table public.model_training_consent_events to supabase_read_only_user';
    execute 'grant select on table public.model_usage_realtime_windows to supabase_read_only_user';
    execute 'grant select on table public.model_priority_runtime_snapshots to supabase_read_only_user';
    execute 'grant select on table public.provider_capacity_windows to supabase_read_only_user';
  end if;
end $$;

-- omitted on CRDB: NOTIFY pgrst (PostgREST)

