-- =============================================================================
-- CockroachDB Cloud — manual SQL upload (Postgres integer semantics)
-- Unqualified INT / INTEGER in this session resolve to INT4 (like PostgreSQL).
-- Apply cockroachdb/bootstrap/crdb_supabase_shim.sql once before the first migration.
-- Generated by: node cockroachdb/scripts/prepare-crdb-upload-sql.mjs
-- =============================================================================
SET default_int_size = 4;


-- =============================================================================
-- Migration: 20260507153000_platform_schema.sql
-- Platform DDL expansion (main application schema)
-- =============================================================================
--
-- Purpose
--   Expands the core backend (20260506160000_core_backend.sql) into the full
--   Clauxen platform data model: identity, workspaces, projects, chat threads,
--   artifacts/files, model usage, RAG embeddings, billing workspace scoping,
--   and operational tables (webhooks, audit, API keys).
--
-- Prerequisites
--   - public.set_updated_at() from core_backend
--   - public.user_settings, user_balances, token_transactions, billing_*,
--     research_runs, rate_limits from core_backend
--
-- What this migration does NOT add (later migrations / app layer)
--   - Agent skills tables (Customize → Skills UI)
--   - Long-term user memory store (only memory_enabled pref on user_settings)
--
-- Execution order (high level)
--   1. Extensions + shared trigger helper
--   2. Domain tables + ALTER extensions to core tables
--   3. Cross-table FK wiring (branches, artifacts, message parts)
--   4. Indexes + storage buckets
--   5. RLS enablement + updated_at triggers
--   6. RLS policies (owner / workspace-member patterns)
--   7. Seed plans catalog
--
-- Security model
--   All new public tables get RLS enabled in bulk; policies default to
--   auth.uid() ownership or workspace membership via workspace_members.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Extensions & shared utilities
-- -----------------------------------------------------------------------------
-- omitted on CRDB: pgcrypto (digest/gen_random_bytes are builtins)
-- omitted on CRDB: native VECTOR type (no pgvector extension)

-- Idempotently attach set_updated_at() to any table passed as regclass.
-- Used in bulk at end of migration for tables with an updated_at column.
create or replace function public.ensure_updated_at_trigger(p_table regclass)
returns void
language plpgsql
as $$
begin
  -- CockroachDB compatibility: dynamic trigger DDL in PL/pgSQL is not supported.
  -- Tables with explicit triggers keep them; bulk trigger attachment is skipped.
  return;
end;
$$;

-- -----------------------------------------------------------------------------
-- Profiles & user identity
-- -----------------------------------------------------------------------------
-- Extends auth.users with app-facing profile fields and links to workspaces.
-- user_settings (core_backend) gains UI prefs including memory_enabled toggle.

-- profiles: 1:1 with auth.users; holds display identity and default workspace.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  avatar_url text,
  locale text not null default 'en',
  timezone text not null default 'UTC',
  default_workspace_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- omitted on CRDB: COMMENT ON metadata

alter table public.user_settings
  add column if not exists display_name text,
  add column if not exists avatar_url text,
  add column if not exists theme text not null default 'system',
  add column if not exists language text not null default 'en',
  add column if not exists timezone text not null default 'UTC',
  add column if not exists chat_model_id text,
  add column if not exists response_style text,
  add column if not exists memory_enabled boolean not null default true,
  add column if not exists web_search_enabled boolean not null default false,
  add column if not exists artifact_auto_open boolean not null default true,
  add column if not exists email_notifications boolean not null default true,
  add column if not exists product_updates boolean not null default true,
  add column if not exists data_training_opt_in boolean not null default false;

-- user_security_events: append-only security audit trail (login, MFA, etc.).
create table if not exists public.user_security_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  event_type text not null,
  ip_address inet,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Workspaces & collaboration
-- -----------------------------------------------------------------------------
-- Multi-tenant container: members, roles, invites, and per-workspace settings.

-- workspaces: top-level tenant; owner_id is the billing/admin principal.
create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique,
  owner_id uuid not null references auth.users(id) on delete cascade,
  plan_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add constraint profiles_default_workspace_fk
  foreign key (default_workspace_id) references public.workspaces(id) on delete set null;
-- omitted on CRDB: COMMENT ON metadata
-- omitted on CRDB: COMMENT ON metadata

-- workspace_roles: custom permission bundles per workspace (key + permissions jsonb).
create table if not exists public.workspace_roles (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  key text not null,
  name text not null,
  permissions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, key)
);

-- workspace_members: user ↔ workspace membership with invite/suspend lifecycle.
create table if not exists public.workspace_members (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member',
  status text not null default 'active' check (status in ('active', 'invited', 'suspended', 'removed')),
  joined_at timestamptz,
  created_at timestamptz not null default now(),
  unique (workspace_id, user_id)
);

-- workspace_invites: email invites; token_hash is the secret, never store raw token.
create table if not exists public.workspace_invites (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  email text not null,
  role text not null default 'member',
  token_hash text not null unique,
  invited_by uuid references auth.users(id) on delete set null,
  expires_at timestamptz not null,
  accepted_at timestamptz,
  created_at timestamptz not null default now()
);

-- workspace_settings: 1:1 policy knobs (models, spend cap, artifact retention).
create table if not exists public.workspace_settings (
  workspace_id uuid primary key references public.workspaces(id) on delete cascade,
  default_model_id text,
  allowed_models text[] not null default '{}',
  spending_limit integer,
  artifact_retention_days integer,
  allow_member_invites boolean not null default true,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- notification_preferences: per-user channel toggles (email, billing, security).
create table if not exists public.notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email_notifications boolean not null default true,
  product_updates boolean not null default true,
  research_complete boolean not null default true,
  billing_alerts boolean not null default true,
  security_alerts boolean not null default true,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- connected_accounts: OAuth / third-party integrations linked to a user.
create table if not exists public.connected_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  provider_account_id text,
  scopes text[] not null default '{}',
  status text not null default 'active' check (status in ('active', 'revoked', 'error')),
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider, provider_account_id)
);

-- -----------------------------------------------------------------------------
-- Projects & chats
-- -----------------------------------------------------------------------------
-- Projects group chats; chats hold threaded messages with optional branches.

-- projects: user- or workspace-scoped folders for organizing conversations.
create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  color text,
  icon text,
  status text not null default 'active' check (status in ('active', 'archived', 'deleted')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- omitted on CRDB: COMMENT ON metadata

-- project_members: collaborators on a shared project.
create table if not exists public.project_members (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member',
  created_at timestamptz not null default now(),
  unique (project_id, user_id)
);

-- chats: conversation session (model, prompts, web search, archive state).
create table if not exists public.chats (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  title text not null default 'New chat',
  status text not null default 'active' check (status in ('active', 'archived', 'deleted')),
  model_id text,
  system_prompt text,
  web_search_enabled boolean not null default false,
  adaptive_thinking_enabled boolean not null default false,
  response_style text,
  starred boolean not null default false,
  archived_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- omitted on CRDB: COMMENT ON metadata

-- chat_branches: forked conversation paths from a root or parent message.
create table if not exists public.chat_branches (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.chats(id) on delete cascade,
  root_message_id uuid,
  parent_branch_id uuid references public.chat_branches(id) on delete set null,
  title text,
  created_from_message_id uuid,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- chat_messages: individual turns (user/assistant/tool) with token accounting.
create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.chats(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  branch_id uuid references public.chat_branches(id) on delete set null,
  parent_message_id uuid references public.chat_messages(id) on delete set null,
  role text not null check (role in ('system', 'user', 'assistant', 'tool')),
  status text not null default 'complete' check (status in ('queued', 'streaming', 'complete', 'failed', 'cancelled')),
  content text,
  content_json jsonb not null default '{}'::jsonb,
  token_count integer not null default 0,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  total_tokens integer generated always as (input_tokens + output_tokens) stored,
  model_id text,
  finish_reason text,
  training_eligible boolean not null default false,
  contains_pii boolean not null default false,
  redaction_status text not null default 'not_required',
  error jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- omitted on CRDB: COMMENT ON metadata

-- Deferred FKs: branches reference messages created in the same migration.
alter table public.chat_branches
  add constraint chat_branches_root_message_fk
  foreign key (root_message_id) references public.chat_messages(id) on delete set null;

alter table public.chat_branches
  add constraint chat_branches_created_from_message_fk
  foreign key (created_from_message_id) references public.chat_messages(id) on delete set null;

-- chat_message_parts: multimodal segments (text, file, artifact, tool) in order.
create table if not exists public.chat_message_parts (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references public.chat_messages(id) on delete cascade,
  type text not null,
  text text,
  json jsonb,
  file_id uuid,
  artifact_id uuid,
  tool_call_id uuid,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

-- chat_message_reactions: per-user emoji or feedback on a message.
create table if not exists public.chat_message_reactions (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references public.chat_messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null,
  created_at timestamptz not null default now(),
  unique (message_id, user_id, reaction)
);

-- pinned_chats: user-specific sidebar ordering for favorite threads.
create table if not exists public.pinned_chats (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.chats(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (chat_id, user_id)
);

-- -----------------------------------------------------------------------------
-- Library & saved prompts
-- -----------------------------------------------------------------------------

-- library_items: bookmarked outputs (chats, artifacts, research) with tags.
create table if not exists public.library_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  source_type text not null,
  source_id uuid,
  title text not null,
  description text,
  tags text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- saved_prompts: reusable prompt templates with variable placeholders.
create table if not exists public.saved_prompts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  title text not null,
  prompt text not null,
  variables jsonb not null default '[]'::jsonb,
  visibility text not null default 'private' check (visibility in ('private', 'workspace', 'public')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Artifacts & user files
-- -----------------------------------------------------------------------------
-- Generated deliverables (apps, docs, images) and uploaded attachments.

-- artifacts: versioned creative outputs linked to chat/message context.
create table if not exists public.artifacts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  chat_id uuid references public.chats(id) on delete set null,
  message_id uuid references public.chat_messages(id) on delete set null,
  title text not null,
  kind text not null check (kind in ('app', 'document', 'spreadsheet', 'presentation', 'image', 'code', 'other')),
  status text not null default 'active' check (status in ('active', 'archived', 'deleted', 'processing', 'failed')),
  current_version_id uuid,
  storage_bucket text,
  storage_path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- omitted on CRDB: COMMENT ON metadata

-- artifact_versions: immutable snapshot per version_number under an artifact.
create table if not exists public.artifact_versions (
  id uuid primary key default gen_random_uuid(),
  artifact_id uuid not null references public.artifacts(id) on delete cascade,
  version_number integer not null,
  storage_bucket text not null,
  storage_path text not null,
  content_hash text,
  metadata jsonb not null default '{}'::jsonb,
  created_by_message_id uuid references public.chat_messages(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (artifact_id, version_number)
);

alter table public.artifacts
  add constraint artifacts_current_version_fk
  foreign key (current_version_id) references public.artifact_versions(id) on delete set null;

-- user_files: uploaded attachments in Supabase Storage (bucket + path unique).
create table if not exists public.user_files (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  original_name text not null,
  mime_type text,
  size_bytes bigint not null default 0,
  storage_bucket text not null,
  storage_path text not null,
  content_hash text,
  status text not null default 'uploaded' check (status in ('pending', 'uploaded', 'processing', 'ready', 'failed', 'deleted')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (storage_bucket, storage_path)
);
-- omitted on CRDB: COMMENT ON metadata

-- file_versions: historical blobs when a file is replaced in place.
create table if not exists public.file_versions (
  id uuid primary key default gen_random_uuid(),
  file_id uuid not null references public.user_files(id) on delete cascade,
  version_number integer not null,
  storage_bucket text not null,
  storage_path text not null,
  size_bytes bigint not null default 0,
  content_hash text,
  created_at timestamptz not null default now(),
  unique (file_id, version_number)
);

-- file_processing_jobs: async pipeline (extract text, embed, virus scan, etc.).
create table if not exists public.file_processing_jobs (
  id uuid primary key default gen_random_uuid(),
  file_id uuid not null references public.user_files(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_type text not null,
  status text not null default 'queued' check (status in ('queued', 'running', 'complete', 'failed', 'cancelled')),
  error jsonb,
  result jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

-- Wire multimodal message parts to files, artifacts, and tool invocations.
alter table public.chat_message_parts
  add constraint chat_message_parts_file_fk
  foreign key (file_id) references public.user_files(id) on delete set null;

alter table public.chat_message_parts
  add constraint chat_message_parts_artifact_fk
  foreign key (artifact_id) references public.artifacts(id) on delete set null;

-- -----------------------------------------------------------------------------
-- Models, tool calls & usage metering
-- -----------------------------------------------------------------------------

-- model_catalog: provider models, pricing, and capability flags for the picker.
create table if not exists public.model_catalog (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  model_id text not null,
  display_name text not null,
  capabilities jsonb not null default '[]'::jsonb,
  input_token_price numeric(12, 8) not null default 0,
  output_token_price numeric(12, 8) not null default 0,
  is_enabled boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, model_id)
);
-- omitted on CRDB: COMMENT ON metadata

-- model_usage_events: append-only inference billing / analytics per request.
create table if not exists public.model_usage_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  chat_id uuid references public.chats(id) on delete set null,
  message_id uuid references public.chat_messages(id) on delete set null,
  provider text not null,
  model_id text not null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  total_tokens integer generated always as (input_tokens + output_tokens) stored,
  cost_amount numeric(12, 6),
  currency text not null default 'USD',
  latency_ms integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- tool_calls: agent tool invocations (input/output, status, latency).
create table if not exists public.tool_calls (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  chat_id uuid references public.chats(id) on delete set null,
  message_id uuid references public.chat_messages(id) on delete set null,
  tool_name text not null,
  provider text,
  input jsonb not null default '{}'::jsonb,
  output jsonb,
  status text not null default 'queued' check (status in ('queued', 'running', 'complete', 'failed', 'cancelled')),
  error jsonb,
  latency_ms integer,
  created_at timestamptz not null default now()
);

alter table public.chat_message_parts
  add constraint chat_message_parts_tool_call_fk
  foreign key (tool_call_id) references public.tool_calls(id) on delete set null;

-- -----------------------------------------------------------------------------
-- Research & RAG (retrieval / “memory” for documents)
-- -----------------------------------------------------------------------------
-- Note: long-term conversational memory is a user_settings flag only here;
-- document_chunks + embeddings back file/chat RAG, not chat history memory.

alter table public.research_runs
  add column if not exists workspace_id uuid references public.workspaces(id) on delete set null,
  add column if not exists chat_id uuid references public.chats(id) on delete set null;

-- research_sources: citations gathered during a research_runs session.
create table if not exists public.research_sources (
  id uuid primary key default gen_random_uuid(),
  research_run_id uuid not null references public.research_runs(id) on delete cascade,
  url text not null,
  title text,
  publisher text,
  published_at timestamptz,
  excerpt text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- document_chunks: text segments from files/chats for semantic search.
create table if not exists public.document_chunks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  source_type text not null,
  source_id uuid,
  chunk_index integer not null,
  content text not null,
  token_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
-- omitted on CRDB: COMMENT ON metadata

-- embeddings: pgvector(1536) vectors keyed to document_chunks (requires vector ext).
create table if not exists public.embeddings (
  id uuid primary key default gen_random_uuid(),
  chunk_id uuid not null references public.document_chunks(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  provider text not null,
  model_id text not null,
  embedding VECTOR(1536),
  dimensions integer not null default 1536,
  created_at timestamptz not null default now()
);
-- omitted on CRDB: COMMENT ON metadata

-- -----------------------------------------------------------------------------
-- Billing extensions (plans, subscriptions, workspace scoping)
-- -----------------------------------------------------------------------------
-- Extends core_backend billing_* tables with workspace_id and provider fields.

-- plans: product catalog (free/pro/team) with INR pricing and feature limits.
create table if not exists public.plans (
  id text primary key,
  name text not null,
  display_name text not null,
  price_paise_monthly integer not null default 0,
  price_paise_yearly integer not null default 0,
  currency text not null default 'INR',
  token_grant integer not null default 0,
  limits jsonb not null default '{}'::jsonb,
  features jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- omitted on CRDB: COMMENT ON metadata

-- subscriptions: user or workspace subscription linked to Razorpay (default).
create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  plan_id text references public.plans(id) on delete set null,
  provider text not null default 'razorpay',
  provider_subscription_id text,
  status text not null default 'trialing',
  billing_cycle text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- omitted on CRDB: COMMENT ON metadata

-- Backfill provider-neutral columns on core billing tables; migrate legacy ids.
alter table public.billing_orders
  add column if not exists workspace_id uuid references public.workspaces(id) on delete set null,
  add column if not exists provider text not null default 'razorpay',
  add column if not exists provider_order_id text;

update public.billing_orders
set provider_order_id = razorpay_order_id
where provider_order_id is null;

alter table public.billing_payments
  add column if not exists workspace_id uuid references public.workspaces(id) on delete set null,
  add column if not exists provider text not null default 'razorpay',
  add column if not exists provider_payment_id text;

update public.billing_payments
set provider_payment_id = id
where provider_payment_id is null;

alter table public.token_transactions
  add column if not exists workspace_id uuid references public.workspaces(id) on delete set null;

alter table public.user_balances
  add column if not exists workspace_id uuid references public.workspaces(id) on delete set null;

-- -----------------------------------------------------------------------------
-- Platform operations & governance
-- -----------------------------------------------------------------------------

-- webhook_events: idempotent ingest log for payment/provider webhooks.
create table if not exists public.webhook_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  event_id text not null,
  event_type text not null,
  payload jsonb not null,
  status text not null default 'received' check (status in ('received', 'processed', 'ignored', 'failed')),
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (provider, event_id)
);

-- audit_logs: cross-cutting activity log (user actions, admin events).
create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  actor_type text not null default 'user',
  action text not null,
  target_type text,
  target_id text,
  ip_address inet,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- api_keys: hashed programmatic keys (prefix shown in UI; never store plaintext).
create table if not exists public.api_keys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  name text not null,
  key_hash text not null unique,
  key_prefix text not null,
  scopes text[] not null default '{}',
  last_used_at timestamptz,
  expires_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

-- abuse_reports: user-submitted moderation tickets with review workflow.
create table if not exists public.abuse_reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  workspace_id uuid references public.workspaces(id) on delete set null,
  category text not null,
  status text not null default 'open' check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- feature_flags: runtime toggles with rollout/condition json for gradual release.
create table if not exists public.feature_flags (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,
  description text,
  enabled boolean not null default false,
  rollout jsonb not null default '{}'::jsonb,
  conditions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Extend core rate_limits with generic subject/action dimensions for API throttling.
alter table public.rate_limits
  add column if not exists subject_type text,
  add column if not exists subject_id text,
  add column if not exists action text;

-- -----------------------------------------------------------------------------
-- Indexes (query paths for lists, lookups, and RLS subqueries)
-- -----------------------------------------------------------------------------

create index if not exists profiles_email_idx on public.profiles (email);

create index if not exists workspaces_owner_idx on public.workspaces (owner_id);

create index if not exists workspace_members_user_idx on public.workspace_members (user_id);

create index if not exists projects_user_idx on public.projects (user_id, updated_at desc);

create index if not exists chats_user_updated_idx on public.chats (user_id, updated_at desc);

create index if not exists chats_workspace_updated_idx on public.chats (workspace_id, updated_at desc);

create index if not exists chat_messages_chat_created_idx on public.chat_messages (chat_id, created_at);

create index if not exists chat_messages_branch_created_idx on public.chat_messages (branch_id, created_at);

create index if not exists chat_message_parts_message_position_idx on public.chat_message_parts (message_id, position);

create index if not exists artifacts_user_updated_idx on public.artifacts (user_id, updated_at desc);

create index if not exists user_files_user_created_idx on public.user_files (user_id, created_at desc);

create index if not exists model_usage_user_created_idx on public.model_usage_events (user_id, created_at desc);

create index if not exists tool_calls_message_idx on public.tool_calls (message_id, created_at);

create index if not exists document_chunks_source_idx on public.document_chunks (source_type, source_id, chunk_index);

create index if not exists embeddings_chunk_idx on public.embeddings (chunk_id);

create index if not exists audit_logs_workspace_created_idx on public.audit_logs (workspace_id, created_at desc);

create index if not exists webhook_events_provider_event_idx on public.webhook_events (provider, event_id);

-- -----------------------------------------------------------------------------
-- Supabase Storage buckets
-- -----------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values
  ('generated-images', 'generated-images', false),
  ('exports', 'exports', false)
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- Row Level Security: enable on all platform tables
-- -----------------------------------------------------------------------------

do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles', 'user_settings', 'user_security_events', 'workspaces', 'workspace_roles',
    'workspace_members', 'workspace_invites', 'workspace_settings', 'notification_preferences',
    'connected_accounts', 'projects', 'project_members', 'chats', 'chat_branches',
    'chat_messages', 'chat_message_parts', 'chat_message_reactions', 'pinned_chats',
    'library_items', 'saved_prompts', 'artifacts', 'artifact_versions', 'user_files',
    'file_versions', 'file_processing_jobs', 'model_catalog', 'model_usage_events',
    'tool_calls', 'research_runs', 'research_sources', 'document_chunks', 'embeddings',
    'plans', 'subscriptions', 'billing_orders', 'billing_payments', 'token_transactions',
    'user_balances', 'rate_limits', 'webhook_events', 'audit_logs', 'api_keys',
    'abuse_reports', 'feature_flags'
  ] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- updated_at triggers (tables with updated_at column)
-- -----------------------------------------------------------------------------

do $$
declare
  r record;
begin
  for r in
    select table_name
    from information_schema.columns
    where table_schema = 'public'
      and column_name = 'updated_at'
      and table_name in (
        'profiles', 'workspaces', 'workspace_roles', 'workspace_settings',
        'notification_preferences', 'connected_accounts', 'projects', 'chats',
        'chat_messages', 'library_items', 'saved_prompts', 'artifacts',
        'user_files', 'file_processing_jobs', 'model_catalog', 'plans',
        'subscriptions', 'abuse_reports', 'feature_flags'
      )
  loop
    select public.ensure_updated_at_trigger(format('public.%I', r.table_name)::regclass);
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- RLS policies
-- -----------------------------------------------------------------------------
-- Patterns:
--   - "own_*"     → auth.uid() matches user_id / id
--   - workspace   → owner_id or active workspace_members row
--   - read-only   → model_catalog, plans, feature_flags (enabled only)
-- -----------------------------------------------------------------------------

-- --- Profiles & workspaces ---

drop policy if exists "profiles_manage_own" on public.profiles;

create policy "profiles_manage_own" on public.profiles
for all to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "workspaces_read_member" on public.workspaces;

create policy "workspaces_read_member" on public.workspaces
for select to authenticated
using (owner_id = auth.uid() or exists (
  select 1 from public.workspace_members wm
  where wm.workspace_id = workspaces.id and wm.user_id = auth.uid() and wm.status = 'active'
));

drop policy if exists "workspaces_owner_write" on public.workspaces;

create policy "workspaces_owner_write" on public.workspaces
for all to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

-- --- Workspace members & invites ---

drop policy if exists "workspace_members_read_member" on public.workspace_members;

create policy "workspace_members_read_member" on public.workspace_members
for select to authenticated
using (user_id = auth.uid() or exists (
  select 1 from public.workspaces w where w.id = workspace_members.workspace_id and w.owner_id = auth.uid()
));

drop policy if exists "workspace_members_owner_write" on public.workspace_members;

create policy "workspace_members_owner_write" on public.workspace_members
for all to authenticated
using (exists (select 1 from public.workspaces w where w.id = workspace_members.workspace_id and w.owner_id = auth.uid()))
with check (exists (select 1 from public.workspaces w where w.id = workspace_members.workspace_id and w.owner_id = auth.uid()));

drop policy if exists "workspace_invites_owner_write" on public.workspace_invites;

create policy "workspace_invites_owner_write" on public.workspace_invites
for all to authenticated
using (exists (select 1 from public.workspaces w where w.id = workspace_invites.workspace_id and w.owner_id = auth.uid()))
with check (exists (select 1 from public.workspaces w where w.id = workspace_invites.workspace_id and w.owner_id = auth.uid()));

drop policy if exists "workspace_scoped_read" on public.workspace_settings;

create policy "workspace_scoped_read" on public.workspace_settings
for select to authenticated
using (exists (
  select 1 from public.workspace_members wm
  where wm.workspace_id = workspace_settings.workspace_id and wm.user_id = auth.uid() and wm.status = 'active'
) or exists (select 1 from public.workspaces w where w.id = workspace_settings.workspace_id and w.owner_id = auth.uid()));

drop policy if exists "workspace_settings_owner_write" on public.workspace_settings;

create policy "workspace_settings_owner_write" on public.workspace_settings
for all to authenticated
using (exists (select 1 from public.workspaces w where w.id = workspace_settings.workspace_id and w.owner_id = auth.uid()))
with check (exists (select 1 from public.workspaces w where w.id = workspace_settings.workspace_id and w.owner_id = auth.uid()));

-- --- User prefs & integrations ---

drop policy if exists "own_notification_preferences" on public.notification_preferences;

create policy "own_notification_preferences" on public.notification_preferences
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "own_connected_accounts" on public.connected_accounts;

create policy "own_connected_accounts" on public.connected_accounts
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "own_security_events_read" on public.user_security_events;

create policy "own_security_events_read" on public.user_security_events
for select to authenticated
using (auth.uid() = user_id);

-- --- Catalog reads (authenticated, filtered) ---

drop policy if exists "model_catalog_read" on public.model_catalog;

create policy "model_catalog_read" on public.model_catalog
for select to authenticated
using (is_enabled = true);

drop policy if exists "plans_read_active" on public.plans;

create policy "plans_read_active" on public.plans
for select to authenticated
using (is_active = true);

-- --- Projects & chats ---

drop policy if exists "own_projects" on public.projects;

create policy "own_projects" on public.projects
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "own_project_members" on public.project_members;

create policy "own_project_members" on public.project_members
for all to authenticated
using (auth.uid() = user_id or exists (select 1 from public.projects p where p.id = project_members.project_id and p.user_id = auth.uid()))
with check (auth.uid() = user_id or exists (select 1 from public.projects p where p.id = project_members.project_id and p.user_id = auth.uid()));

drop policy if exists "own_chats" on public.chats;

create policy "own_chats" on public.chats
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "own_chat_branches" on public.chat_branches;

create policy "own_chat_branches" on public.chat_branches
for all to authenticated
using (exists (select 1 from public.chats c where c.id = chat_branches.chat_id and c.user_id = auth.uid()))
with check (exists (select 1 from public.chats c where c.id = chat_branches.chat_id and c.user_id = auth.uid()));

drop policy if exists "own_chat_messages" on public.chat_messages;

create policy "own_chat_messages" on public.chat_messages
for all to authenticated
using (auth.uid() = user_id or exists (select 1 from public.chats c where c.id = chat_messages.chat_id and c.user_id = auth.uid()))
with check (auth.uid() = user_id or exists (select 1 from public.chats c where c.id = chat_messages.chat_id and c.user_id = auth.uid()));

drop policy if exists "own_chat_message_parts" on public.chat_message_parts;

create policy "own_chat_message_parts" on public.chat_message_parts
for all to authenticated
using (exists (
  select 1 from public.chat_messages m join public.chats c on c.id = m.chat_id
  where m.id = chat_message_parts.message_id and c.user_id = auth.uid()
))
with check (exists (
  select 1 from public.chat_messages m join public.chats c on c.id = m.chat_id
  where m.id = chat_message_parts.message_id and c.user_id = auth.uid()
));

drop policy if exists "own_chat_message_reactions" on public.chat_message_reactions;

create policy "own_chat_message_reactions" on public.chat_message_reactions
for all to authenticated
using (auth.uid() = user_id or exists (
  select 1 from public.chat_messages m join public.chats c on c.id = m.chat_id
  where m.id = chat_message_reactions.message_id and c.user_id = auth.uid()
))
with check (auth.uid() = user_id);

drop policy if exists "own_pinned_chats" on public.pinned_chats;

create policy "own_pinned_chats" on public.pinned_chats
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- --- Library, prompts, artifacts, files ---

drop policy if exists "own_library_items" on public.library_items;

create policy "own_library_items" on public.library_items
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "own_saved_prompts" on public.saved_prompts;

create policy "own_saved_prompts" on public.saved_prompts
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "own_artifacts" on public.artifacts;

create policy "own_artifacts" on public.artifacts
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "own_artifact_versions" on public.artifact_versions;

create policy "own_artifact_versions" on public.artifact_versions
for all to authenticated
using (exists (select 1 from public.artifacts a where a.id = artifact_versions.artifact_id and a.user_id = auth.uid()))
with check (exists (select 1 from public.artifacts a where a.id = artifact_versions.artifact_id and a.user_id = auth.uid()));

drop policy if exists "own_user_files" on public.user_files;

create policy "own_user_files" on public.user_files
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "own_file_versions" on public.file_versions;

create policy "own_file_versions" on public.file_versions
for all to authenticated
using (exists (select 1 from public.user_files f where f.id = file_versions.file_id and f.user_id = auth.uid()))
with check (exists (select 1 from public.user_files f where f.id = file_versions.file_id and f.user_id = auth.uid()));

drop policy if exists "own_file_processing_jobs" on public.file_processing_jobs;

create policy "own_file_processing_jobs" on public.file_processing_jobs
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- --- Usage, tools, research, RAG ---

drop policy if exists "own_model_usage_events" on public.model_usage_events;

create policy "own_model_usage_events" on public.model_usage_events
for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "own_tool_calls" on public.tool_calls;

create policy "own_tool_calls" on public.tool_calls
for all to authenticated
using (auth.uid() = user_id or exists (
  select 1 from public.chat_messages m join public.chats c on c.id = m.chat_id
  where m.id = tool_calls.message_id and c.user_id = auth.uid()
))
with check (auth.uid() = user_id or exists (
  select 1 from public.chat_messages m join public.chats c on c.id = m.chat_id
  where m.id = tool_calls.message_id and c.user_id = auth.uid()
));

drop policy if exists "own_research_sources" on public.research_sources;

create policy "own_research_sources" on public.research_sources
for all to authenticated
using (exists (select 1 from public.research_runs rr where rr.id = research_sources.research_run_id and rr.user_id = auth.uid()))
with check (exists (select 1 from public.research_runs rr where rr.id = research_sources.research_run_id and rr.user_id = auth.uid()));

drop policy if exists "own_document_chunks" on public.document_chunks;

create policy "own_document_chunks" on public.document_chunks
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "own_embeddings" on public.embeddings;

create policy "own_embeddings" on public.embeddings
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- --- Billing & platform governance ---

drop policy if exists "own_subscriptions" on public.subscriptions;

create policy "own_subscriptions" on public.subscriptions
for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "own_api_keys" on public.api_keys;

create policy "own_api_keys" on public.api_keys
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "own_abuse_reports" on public.abuse_reports;

create policy "own_abuse_reports" on public.abuse_reports
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "audit_logs_owner_read" on public.audit_logs;

create policy "audit_logs_owner_read" on public.audit_logs
for select to authenticated
using (auth.uid() = user_id or exists (
  select 1 from public.workspaces w where w.id = audit_logs.workspace_id and w.owner_id = auth.uid()
));

drop policy if exists "feature_flags_authenticated_read" on public.feature_flags;

create policy "feature_flags_authenticated_read" on public.feature_flags
for select to authenticated
using (enabled = true);

-- -----------------------------------------------------------------------------
-- Seed data: default subscription plans
-- -----------------------------------------------------------------------------

insert into public.plans (id, name, display_name, price_paise_monthly, price_paise_yearly, currency, token_grant, limits, features)
values
  ('free', 'Free', 'Free', 0, 0, 'INR', 5000, '{"monthlyMessages": 100, "storageGb": 1}'::jsonb, '["chat", "artifacts"]'::jsonb),
  ('pro', 'Pro', 'Pro', 199900, 1999000, 'INR', 200000, '{"monthlyMessages": 5000, "storageGb": 25}'::jsonb, '["chat", "artifacts", "research", "image_generation"]'::jsonb),
  ('team', 'Team', 'Team', 499900, 4999000, 'INR', 800000, '{"monthlyMessages": 25000, "storageGb": 100}'::jsonb, '["chat", "artifacts", "research", "team_workspaces"]'::jsonb)
on conflict (id) do update set
  display_name = excluded.display_name,
  price_paise_monthly = excluded.price_paise_monthly,
  price_paise_yearly = excluded.price_paise_yearly,
  token_grant = excluded.token_grant,
  limits = excluded.limits,
  features = excluded.features,
  updated_at = now();
