-- =============================================================================
-- CockroachDB Cloud — manual SQL upload (Postgres integer semantics)
-- Unqualified INT / INTEGER in this session resolve to INT4 (like PostgreSQL).
-- Apply cockroachdb/bootstrap/crdb_supabase_shim.sql once before the first migration.
-- Generated by: node cockroachdb/scripts/prepare-crdb-upload-sql.mjs
-- =============================================================================
SET default_int_size = 4;


-- CRDB upload: Supabase-only migration (HypoPg, pg_cron, extension-heavy tuning).
-- Omitted for CockroachDB; schema is unchanged by this placeholder.
SELECT 1 AS crdb_upload_noop;
