-- =============================================================================
-- CockroachDB Cloud — manual SQL upload (Postgres integer semantics)
-- Unqualified INT / INTEGER in this session resolve to INT4 (like PostgreSQL).
-- Apply cockroachdb/bootstrap/crdb_supabase_shim.sql once before the first migration.
-- Generated by: node cockroachdb/scripts/prepare-crdb-upload-sql.mjs
-- =============================================================================
SET default_int_size = 4;


-- =============================================================================
-- Migration: 20260507110000_parallel_research
-- Purpose: Introduce public.research_runs for Parallel deep-research jobs and
--          extend token_transactions.source to bill deep_research usage.
-- Prerequisites:
--   - public.token_transactions exists (core billing schema).
--   - auth.users available for FK on research_runs.user_id.
-- Apply-time behavior:
--   - Creates research_runs with provider/status CHECK constraints.
--   - Enables RLS with owner-scoped SELECT/INSERT/UPDATE policies.
--   - Adds listing and idempotency indexes.
--   - Replaces token_transactions_source_check to include 'deep_research'.
-- Security / RLS:
--   - research_runs: authenticated users may only read/write rows where
--     auth.uid() = user_id. No DELETE policy (rows retained for audit).
--   - token_transactions change is a CHECK only; existing RLS unchanged.
-- Rollback guidance:
--   - DROP TABLE public.research_runs CASCADE (loses run history).
--   - Restore prior token_transactions_source_check without 'deep_research'
--     if billing must not reference that source label.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Table: research_runs
-- Tracks async Parallel API research jobs per user.
-- -----------------------------------------------------------------------------
create table if not exists public.research_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'parallel',
  provider_run_id text not null,
  objective text not null,
  processor text not null default 'base',
  status text not null default 'queued',
  result jsonb,
  error jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Idempotent upsert per external provider run id.
  unique (provider, provider_run_id),
  -- Provider enum: only Parallel is supported today.
  constraint research_runs_provider_check check (provider in ('parallel')),
  -- Lifecycle aligned with Parallel webhook/status vocabulary.
  constraint research_runs_status_check check (
    status in ('queued', 'action_required', 'running', 'completed', 'failed', 'cancelling', 'cancelled')
  )
);

-- -----------------------------------------------------------------------------
-- Row level security: owner-only access
-- -----------------------------------------------------------------------------
alter table public.research_runs enable row level security;

drop policy if exists "research_runs_select_own" on public.research_runs;

create policy "research_runs_select_own"
on public.research_runs for select
using (auth.uid() = user_id);

drop policy if exists "research_runs_insert_own" on public.research_runs;

create policy "research_runs_insert_own"
on public.research_runs for insert
with check (auth.uid() = user_id);

drop policy if exists "research_runs_update_own" on public.research_runs;

create policy "research_runs_update_own"
on public.research_runs for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- Indexes: user history and provider idempotency
-- -----------------------------------------------------------------------------
create index if not exists research_runs_user_created_idx
on public.research_runs (user_id, created_at desc);

create index if not exists research_runs_provider_run_idx
on public.research_runs (provider, provider_run_id);

-- -----------------------------------------------------------------------------
-- Billing: allow deep_research as a token debit source
-- -----------------------------------------------------------------------------
alter table public.token_transactions
drop constraint if exists token_transactions_source_check;

alter table public.token_transactions
add constraint token_transactions_source_check check (
  source in ('purchase', 'generation', 'chat', 'reward', 'web_search', 'web_extract', 'deep_research')
);
