-- =============================================================================
-- CockroachDB Cloud — manual SQL upload (Postgres integer semantics)
-- Unqualified INT / INTEGER in this session resolve to INT4 (like PostgreSQL).
-- Apply cockroachdb/bootstrap/crdb_supabase_shim.sql once before the first migration.
-- Generated by: node cockroachdb/scripts/prepare-crdb-upload-sql.mjs
-- =============================================================================
SET default_int_size = 4;


-- =============================================================================
-- Migration: 20260507203000_performance_advisor_rls_cleanup
-- Purpose: Performance Advisor RLS optimizations:
--   1) Rewrite auth.uid() to (select auth.uid()) in all public policies so the
--      planner evaluates JWT once per statement, not per row.
--   2) Split workspace FOR ALL owner policies into action-specific INSERT/UPDATE/
--      DELETE policies to avoid duplicate SELECT evaluation for authenticated.
-- Prerequisites:
--   - public tables with existing RLS policies referencing auth.uid().
--   - workspace read policies from prior migrations remain after this runs.
-- Apply-time behavior:
--   - Dynamic DO loop recreates policies from pg_policies catalog.
--   - Drops workspaces_owner_write / workspace_*_owner_write; creates granular
--     owner_insert/update/delete policies.
-- Security / RLS:
--   - Semantically equivalent access; performance-only change for auth.uid().
-- Rollback guidance:
--   - Restore prior policy definitions from git (advisor may warn on FOR ALL).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Batch rewrite: auth.uid() -> (select auth.uid()) on all public policies
-- -----------------------------------------------------------------------------
-- CRDB: omitted bulk policy rewrite via pg_policies (not portable)


-- -----------------------------------------------------------------------------
-- workspaces: replace FOR ALL owner_write with action-specific policies
-- -----------------------------------------------------------------------------
drop policy if exists "workspaces_owner_write" on public.workspaces;

drop policy if exists "workspaces_owner_insert" on public.workspaces;

create policy "workspaces_owner_insert"
on public.workspaces
for insert
to authenticated
with check (owner_id = (select auth.uid()));

drop policy if exists "workspaces_owner_update" on public.workspaces;

create policy "workspaces_owner_update"
on public.workspaces
for update
to authenticated
using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));

drop policy if exists "workspaces_owner_delete" on public.workspaces;

create policy "workspaces_owner_delete"
on public.workspaces
for delete
to authenticated
using (owner_id = (select auth.uid()));

-- -----------------------------------------------------------------------------
-- workspace_members: action-specific owner policies
-- -----------------------------------------------------------------------------
drop policy if exists "workspace_members_owner_write" on public.workspace_members;

drop policy if exists "workspace_members_owner_insert" on public.workspace_members;

create policy "workspace_members_owner_insert"
on public.workspace_members
for insert
to authenticated
with check (
  exists (
    select 1
    from public.workspaces w
    where w.id = workspace_members.workspace_id
      and w.owner_id = (select auth.uid())
  )
);

drop policy if exists "workspace_members_owner_update" on public.workspace_members;

create policy "workspace_members_owner_update"
on public.workspace_members
for update
to authenticated
using (
  exists (
    select 1
    from public.workspaces w
    where w.id = workspace_members.workspace_id
      and w.owner_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.workspaces w
    where w.id = workspace_members.workspace_id
      and w.owner_id = (select auth.uid())
  )
);

drop policy if exists "workspace_members_owner_delete" on public.workspace_members;

create policy "workspace_members_owner_delete"
on public.workspace_members
for delete
to authenticated
using (
  exists (
    select 1
    from public.workspaces w
    where w.id = workspace_members.workspace_id
      and w.owner_id = (select auth.uid())
  )
);

-- -----------------------------------------------------------------------------
-- workspace_settings: action-specific owner policies
-- -----------------------------------------------------------------------------
drop policy if exists "workspace_settings_owner_write" on public.workspace_settings;

drop policy if exists "workspace_settings_owner_insert" on public.workspace_settings;

create policy "workspace_settings_owner_insert"
on public.workspace_settings
for insert
to authenticated
with check (
  exists (
    select 1
    from public.workspaces w
    where w.id = workspace_settings.workspace_id
      and w.owner_id = (select auth.uid())
  )
);

drop policy if exists "workspace_settings_owner_update" on public.workspace_settings;

create policy "workspace_settings_owner_update"
on public.workspace_settings
for update
to authenticated
using (
  exists (
    select 1
    from public.workspaces w
    where w.id = workspace_settings.workspace_id
      and w.owner_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.workspaces w
    where w.id = workspace_settings.workspace_id
      and w.owner_id = (select auth.uid())
  )
);

drop policy if exists "workspace_settings_owner_delete" on public.workspace_settings;

create policy "workspace_settings_owner_delete"
on public.workspace_settings
for delete
to authenticated
using (
  exists (
    select 1
    from public.workspaces w
    where w.id = workspace_settings.workspace_id
      and w.owner_id = (select auth.uid())
  )
);
